import Link from "next/link";

import { formatMoney } from "@/lib/money";
import { requireUser } from "@/server/auth";
import { getPoultryAnalytics, type PoultryPeriod } from "@/server/poultry";

const periods: Record<PoultryPeriod, string> = { TODAY: "Сегодня", WEEK: "Неделя", MONTH: "Месяц", YEAR: "Год", ALL: "Всё" };

export default async function PoultryAnalyticsPage({ searchParams }: { searchParams: Promise<{ period?: string; tab?: string; from?: string; to?: string }> }) {
  const user = await requireUser();
  const params = await searchParams;
  const period = params.period && params.period in periods ? params.period as PoultryPeriod : "MONTH";
  const tab = ["money", "flock", "cost"].includes(params.tab ?? "") ? params.tab! : "money";
  const custom = params.from && params.to ? { from: params.from, to: params.to } : undefined;
  const data = await getPoultryAnalytics(user.id, period, custom);
  const categoryAmount = (...needles: string[]) => data.report.expensesByCategory.filter((item) => needles.some((needle) => item.name.toLocaleLowerCase("ru-RU").includes(needle))).reduce((sum, item) => sum + Number(item.amount), 0).toFixed(2);
  const periodSales = data.sales.filter((sale) => sale.operationDate >= data.range.from && sale.operationDate <= data.range.to);
  const birdSales = periodSales.filter((sale) => sale.saleType !== "EGGS");
  const tabHref = (nextTab: string) => `/poultry/analytics?period=${period}&tab=${nextTab}${custom ? `&from=${custom.from}&to=${custom.to}` : ""}`;

  return <>
    <header className="page-header compact-page-header"><div><p className="eyebrow">Птицеводство</p><h1>Аналитика</h1><p className="muted">Деньги, поголовье и себестоимость отдельно</p></div></header>
    <form className="period-tabs" action="/poultry/analytics"><input type="hidden" name="tab" value={tab}/>{Object.entries(periods).map(([value, label]) => <button key={value} name="period" value={value} className={!custom && period === value ? "active" : ""}>{label}</button>)}</form>
    <details className="optional-details analytics-custom-period" open={Boolean(custom)}><summary>Свой период</summary><form action="/poultry/analytics" className="inline-form"><input type="hidden" name="tab" value={tab}/><label>С<input type="date" name="from" required defaultValue={params.from}/></label><label>По<input type="date" name="to" required defaultValue={params.to}/></label><button className="button secondary">Показать</button></form></details>
    <nav className="segment-tabs"><Link href={tabHref("money")} className={tab === "money" ? "active" : ""}>Деньги</Link><Link href={tabHref("flock")} className={tab === "flock" ? "active" : ""}>Поголовье</Link><Link href={tabHref("cost")} className={tab === "cost" ? "active" : ""}>Себестоимость</Link></nav>
    {tab === "money" && <><section className="metric-grid analytics-grid"><article><span>Доходы</span><strong className="income">{formatMoney(data.report.income)}</strong></article><article><span>Расходы</span><strong className="expense">{formatMoney(data.report.expense)}</strong></article><article><span>Результат</span><strong>{formatMoney(data.report.result)}</strong></article><article><span>Продажи птицы</span><strong>{formatMoney(birdSales.reduce((sum, sale) => sum + Number(sale.totalAmount), 0).toFixed(2))}</strong></article><article><span>Продажи яиц</span><strong>{formatMoney(data.eggStats.income.toFixed(2))}</strong></article><article><span>Корм</span><strong>{formatMoney(categoryAmount("корм"))}</strong></article><article><span>Добавки / ветеринария</span><strong>{formatMoney(categoryAmount("добав", "ветерин", "препарат"))}</strong></article><article><span>Оборудование</span><strong>{formatMoney(categoryAmount("оборуд", "материал"))}</strong></article></section>{data.report.expensesByCategory.length > 0 && <div className="compact-list">{data.report.expensesByCategory.map((item) => <article className="compact-list-row" key={item.name}><span><b>{item.name}</b><small>Расход за выбранный период</small></span><strong className="expense">−{formatMoney(item.amount)}</strong></article>)}</div>}</>}
    {tab === "flock" && <><section className="metric-grid analytics-grid"><article><span>Сейчас</span><strong>{data.flock.current}</strong></article><article><span>Продано птицы</span><strong>{data.flock.sold}</strong></article><article><span>Падёж</span><strong>{data.flock.mortality}</strong></article><article><span>Семья / забой</span><strong>{data.flock.family}</strong></article><article><span>Яиц собрано</span><strong>{data.eggStats.collected}</strong></article><article><span>Яиц продано</span><strong>{data.eggStats.sold}</strong></article></section><section className="metric-grid analytics-grid"><article><span>Инкубаций</span><strong>{data.incubationStats.count}</strong></article><article><span>Яиц заложено</span><strong>{data.incubationStats.eggs}</strong></article><article><span>Выведено</span><strong>{data.incubationStats.hatched}</strong></article><article><span>Процент вывода</span><strong>{data.incubationStats.eggs ? Math.round(data.incubationStats.hatched / data.incubationStats.eggs * 100) : 0}%</strong></article></section></>}
    {tab === "cost" && <><div className="compact-list">{data.batches.filter((batch) => batch.status === "ACTIVE").map((batch) => <Link href={`/poultry/flock/${batch.id}`} className="compact-list-row" key={batch.id}><span><b>{batch.name}</b><small>{batch.currentQuantity} голов · корм {formatMoney(batch.feedCost.toFixed(2))} · всего {formatMoney(batch.productionCost.total.toFixed(2))}</small></span><strong>{batch.currentQuantity ? formatMoney((batch.productionCost.total / batch.currentQuantity).toFixed(2)) : "—"}/гол.</strong></Link>)}</div><section className="compact-section"><div className="compact-section-heading"><h2>Остатки и средняя цена корма</h2><Link href="/poultry/feed/stock" className="text-link">Склад →</Link></div><div className="compact-list">{data.inventory.map((item) => <article className="compact-list-row" key={item.product.id}><span><b>{item.product.name}</b><small>{item.current.toFixed(1)} кг в остатке</small></span><strong>{formatMoney(item.averageCostPerKg.toFixed(2))}/кг</strong></article>)}</div></section></>}
  </>;
}
