import Link from "next/link";

import { EmptyState } from "@/components/ui/empty-state";
import { StatusBadge } from "@/components/ui/app-card";
import { todayInputValue } from "@/lib/dates";
import { requireUser } from "@/server/auth";
import { getPoultryDashboard } from "@/server/poultry";
import { createBatchFromIncubationAction, createIncubationAction, updateIncubationItemAction } from "../actions";

export default async function IncubationPage() { const user = await requireUser(); const { incubations } = await getPoultryDashboard(user.id); return <><header className="page-header"><div><p className="eyebrow">Птицеводство</p><h1>Инкубация</h1><p className="muted">Одна закладка может содержать несколько пород.</p></div><Link href="/poultry" className="button secondary">Назад</Link></header><section className="app-card"><h2>Новая закладка</h2><form action={createIncubationAction} className="compact-form"><div className="form-grid"><label>Название / номер<input name="name" required placeholder="Закладка 30 июня"/></label><label>Вид птицы<input name="birdType" required placeholder="Куры"/></label></div><div className="form-grid"><label>Дата закладки<input name="setDate" type="date" required defaultValue={todayInputValue()}/></label><label>Комментарий<input name="comment" placeholder="Необязательно"/></label></div><p className="summary-note">Добавьте одну или несколько пород.</p>{[0,1,2,3].map((index) => <div className="form-grid" key={index}><label>Порода<input name={`breed-${index}`} required={index===0} placeholder={index===0 ? "R3A" : "Не добавлять"}/></label><label>Заложено яиц<input name={`setQuantity-${index}`} required={index===0} inputMode="numeric"/></label></div>)}<button className="button primary">Создать закладку</button></form></section><section className="section-header"><div><p className="eyebrow">Закладки</p><h2>Инкубация и вывод</h2></div></section><div className="transaction-list">{incubations.map((batch) => <article className="app-card" key={batch.id}><div className="card-title"><h3>{batch.name}</h3><StatusBadge tone={batch.status === "ACTIVE" ? "success" : "neutral"}>{batch.status === "ACTIVE" ? "Активна" : "Завершена"}</StatusBadge></div><p className="muted">{batch.birdType} · {batch.setDate.toLocaleDateString("ru-RU")}</p>{batch.items.map((item) => <div className="incubation-item" key={item.id}><b>{item.breed} · вывод {item.hatchedQuantity}/{item.setQuantity} ({item.hatchRate}%)</b><form action={updateIncubationItemAction} className="inline-form"><input type="hidden" name="itemId" value={item.id}/><label>Неоплод<input name="infertileQuantity" inputMode="numeric" defaultValue={item.infertileQuantity}/></label><label>Потери<input name="lossQuantity" inputMode="numeric" defaultValue={item.lossQuantity}/></label><label>Вылупилось<input name="hatchedQuantity" inputMode="numeric" defaultValue={item.hatchedQuantity}/></label><button className="text-link">Сохранить</button></form>{item.hatchedQuantity > 0 && <form action={createBatchFromIncubationAction}><input type="hidden" name="itemId" value={item.id}/><button className="text-link">Создать партию из вывода</button></form>}</div>)}</article>)}</div>{incubations.length === 0 && <EmptyState title="Закладок пока нет" description="Создайте первую закладку, чтобы учитывать породы, неоплод и вылупление."/>}</>; }
