import Link from "next/link";

import { PoultryFormActions } from "@/components/poultry-form-actions";
import { EmptyState } from "@/components/ui/empty-state";
import { StatusBadge } from "@/components/ui/app-card";
import { todayInputValue } from "@/lib/dates";
import { requireUser } from "@/server/auth";
import { getPoultryDashboard } from "@/server/poultry";
import { createIncubationAction } from "../actions";

export default async function IncubationPage() { const user = await requireUser(); const { incubations } = await getPoultryDashboard(user.id); const returnTo = "/poultry/incubation"; return <><header className="page-header"><div><p className="eyebrow">Птицеводство</p><h1>Инкубация</h1><p className="muted">Закладка существует до появления птицы. Партия создаётся после фактического вывода.</p></div><Link href="/poultry" className="button secondary">Обзор</Link></header><section id="new" className="app-card"><h2>Новая закладка</h2><form action={createIncubationAction} className="compact-form"><input type="hidden" name="returnTo" value={returnTo}/><div className="form-grid"><label>Название<input name="name" required placeholder="Закладка 30 июня"/></label><label>Вид птицы<input name="birdType" required placeholder="Куры"/></label></div><div className="form-grid"><label>Дата закладки<input name="setDate" type="date" required defaultValue={todayInputValue()}/></label><label>Источник яиц<select name="eggSource"><option value="OWN">Свои</option><option value="PURCHASED">Купленные</option><option value="GIFTED">Подаренные</option></select></label></div><div className="form-grid"><label>Оплачено, ₴<input name="cashCost" inputMode="decimal" placeholder="Только для купленных"/></label><label>Расчётная стоимость, ₴<input name="productionCost" inputMode="decimal" placeholder="Для своих / подаренных"/></label></div><p className="summary-note">Оплата создаёт один расход. Расчётная стоимость влияет только на себестоимость будущей птицы.</p>{[0,1,2,3].map((index) => <div className="form-grid" key={index}><label>Порода<input name={`breed-${index}`} placeholder={index===0 ? "Необязательно" : "Ещё порода"}/></label><label>Заложено яиц<input name={`setQuantity-${index}`} required={index===0} inputMode="numeric"/></label></div>)}<label>Комментарий<input name="comment"/></label><PoultryFormActions cancelHref={returnTo}><button className="button primary">Создать закладку</button></PoultryFormActions></form></section><section className="section-header"><div><p className="eyebrow">Закладки</p><h2>Инкубация и вывод</h2></div></section><div className="transaction-list">{incubations.map((batch) => <Link className="project-card active" href={`/poultry/incubation/${batch.id}`} key={batch.id}><div className="card-title"><h3>{batch.name}</h3><StatusBadge tone={batch.status === "ACTIVE" ? "success" : "neutral"}>{batch.status === "ACTIVE" ? "Активна" : "Завершена"}</StatusBadge></div><span>{batch.birdType} · {batch.setDate.toLocaleDateString("ru-RU")}</span><strong>{batch.items.reduce((total, item) => total + item.setQuantity, 0)} яиц</strong><small>Вылупилось: {batch.items.reduce((total, item) => total + item.hatchedQuantity, 0)}{batch.hatchDate ? ` · ${batch.hatchDate.toLocaleDateString("ru-RU")}` : ""}</small><em>Открыть →</em></Link>)}</div>{incubations.length === 0 && <EmptyState title="Закладок пока нет" description="Создайте первую закладку."/>}</>; }
