import "server-only";

import { CosmetologyClientStatus, CosmetologyContactMethod, CosmetologyInventoryMovementType, CosmetologyPlanStatus, CosmetologyUnit, FinanceModule, Prisma, TransactionType } from "@prisma/client";
import { z } from "zod";

import { periodStart } from "@/features/family/calculations";
import { dateFromInput, todayInputValue } from "@/lib/dates";
import { prisma } from "@/lib/prisma";

const money = z.string().trim().regex(/^\d+(?:[.,]\d{1,2})?$/);
const quantity = z.string().trim().regex(/^\d+(?:[.,]\d{1,3})?$/).refine((value) => new Prisma.Decimal(value.replace(",", ".")).gt(0));
const nonNegativeMoney = z.string().trim().regex(/^\d+(?:[.,]\d{1,2})?$/);
const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const optional = z.string().trim().max(500).nullable();
const decimal = (value: string) => new Prisma.Decimal(value.replace(",", "."));
const zero = new Prisma.Decimal(0);

export const cosmeticItemCategories = ["Ботулотоксин", "Филлер", "Биоревитализант", "Мезопрепарат", "PDRN", "Полимолочная кислота", "Коллагеновый стимулятор", "Шприцы", "Иглы", "Канюли", "Перчатки", "Салфетки", "Физраствор", "Прочее"];
export const cosmeticExpenseCategories = ["Аренда кабинета / салона", "Реклама", "Обучение", "Оборудование", "Мебель", "Хозяйственные расходы", "Интернет / связь", "Поездки", "Проживание", "Транспорт", "Прочее"];
export const procedureCategories = ["Ботулинотерапия", "Контурная пластика", "Мезотерапия", "Биоревитализация", "Коллагеностимуляция", "Массаж", "Консультация", "Другое"];
export const clientSources = ["Instagram", "TikTok", "Facebook", "Google", "Сайт", "По рекомендации", "Другое"];
export const clientMarks = ["Тяжёлый клиент", "Очень лояльный", "Высокий средний чек", "Любит акции", "Часто переносит запись", "Часто опаздывает", "Пришёл по рекомендации"];

export const clientSchema = z.object({ lastName: z.string().trim().min(1).max(80), firstName: z.string().trim().min(1).max(80), phone: z.string().trim().min(5).max(40), birthDate: date.nullable(), contactMethod: z.nativeEnum(CosmetologyContactMethod), contactValue: z.string().trim().max(300).nullable(), source: z.string().trim().max(80).nullable(), status: z.nativeEnum(CosmetologyClientStatus), specialMarks: z.array(z.string().trim().min(1).max(80)).max(7), notes: optional, allergies: optional, contraindications: optional, medicalNotes: optional });
export const itemSchema = z.object({ name: z.string().trim().min(1).max(120), category: z.string().trim().min(1).max(80), brand: z.string().trim().max(80).nullable(), unit: z.nativeEnum(CosmetologyUnit), comment: optional });
export const purchaseSchema = z.object({ itemId: z.string().cuid(), quantity, totalAmount: money, purchaseDate: date, expiryDate: date.nullable(), batchNumber: z.string().trim().max(120).nullable(), comment: optional });
export const inventoryChangeSchema = z.object({ itemId: z.string().cuid(), quantity, operationDate: date, type: z.enum(["WRITE_OFF", "ADJUSTMENT"]), comment: z.string().trim().min(1).max(500) });
export const templateSchema = z.object({ name: z.string().trim().min(1).max(120), category: z.string().trim().min(1).max(80), basePrice: money.nullable(), durationMinutes: z.coerce.number().int().positive().nullable(), comment: optional });
export const templateMaterialSchema = z.object({ templateId: z.string().cuid(), itemId: z.string().cuid(), quantity });
export const visitSchema = z.object({ clientId: z.string().cuid().nullable(), newClientLastName: z.string().trim().max(80).nullable(), newClientFirstName: z.string().trim().max(80).nullable(), newClientPhone: z.string().trim().max(40).nullable(), procedureTemplateId: z.string().cuid().nullable(), procedureName: z.string().trim().min(1).max(120), paymentAmount: nonNegativeMoney, operationDate: date, itemId: z.string().cuid().nullable(), usageQuantity: quantity.nullable(), comment: optional }).superRefine((value, ctx) => { if (!value.clientId && (!value.newClientLastName || !value.newClientFirstName || !value.newClientPhone)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["newClientFirstName"], message: "Выберите или создайте клиента." }); if (Boolean(value.itemId) !== Boolean(value.usageQuantity)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["itemId"], message: "Укажите и материал, и количество." }); });
export const expenseSchema = z.object({ categoryId: z.string().cuid().nullable(), newCategoryName: z.string().trim().min(1).max(80).nullable(), amount: money, operationDate: date, description: z.string().trim().min(1).max(500), comment: optional }).refine((value) => Boolean(value.categoryId || value.newCategoryName), { path: ["categoryId"], message: "Выберите категорию." });
export const planSchema = z.object({ clientId: z.string().cuid(), title: z.string().trim().min(1).max(160), plannedDate: date.nullable(), status: z.nativeEnum(CosmetologyPlanStatus), note: optional });
export const formValue = (formData: FormData, name: string) => { const value = formData.get(name); return typeof value === "string" && value.trim() ? value.trim() : null; };

function phoneLastFour(phone: string) { const digits = phone.replace(/\D/g, ""); if (digits.length < 4) throw new Error("Введите корректный номер телефона."); return digits.slice(-4); }
async function ownedClient(userId: string, id: string) { const client = await prisma.cosmetologyClient.findFirst({ where: { id, userId, deletedAt: null } }); if (!client) throw new Error("Клиент не найден."); return client; }
async function ownedItem(userId: string, id: string) { const item = await prisma.cosmetologyInventoryItem.findFirst({ where: { id, userId, deletedAt: null } }); if (!item) throw new Error("Препарат или расходник не найден."); return item; }
async function ensureCategories(userId: string) { if (!await prisma.cosmetologyExpenseCategory.count({ where: { userId } })) await prisma.cosmetologyExpenseCategory.createMany({ data: cosmeticExpenseCategories.map((name, sortOrder) => ({ userId, name, sortOrder })), skipDuplicates: true }); }

export async function createCosmetologyClient(userId: string, input: z.infer<typeof clientSchema>) { return prisma.cosmetologyClient.create({ data: { userId, ...input, phoneLastFour: phoneLastFour(input.phone), birthDate: input.birthDate ? dateFromInput(input.birthDate) : null } }); }
export async function updateCosmetologyClient(userId: string, id: string, input: z.infer<typeof clientSchema>) { await ownedClient(userId, id); return prisma.cosmetologyClient.update({ where: { id }, data: { ...input, phoneLastFour: phoneLastFour(input.phone), birthDate: input.birthDate ? dateFromInput(input.birthDate) : null } }); }
export async function getCosmetologyClients(userId: string, query = "") { return prisma.cosmetologyClient.findMany({ where: { userId, deletedAt: null, ...(query ? { OR: [{ lastName: { contains: query, mode: "insensitive" } }, { firstName: { contains: query, mode: "insensitive" } }, { phone: { contains: query } }, { phoneLastFour: { equals: query.replace(/\D/g, "").slice(-4) } }] } : {}) }, orderBy: [{ lastName: "asc" }, { firstName: "asc" }] }); }

export async function createCosmetologyItem(userId: string, input: z.infer<typeof itemSchema>) { const exists = await prisma.cosmetologyInventoryItem.findFirst({ where: { userId, name: { equals: input.name, mode: "insensitive" }, deletedAt: null } }); if (exists) throw new Error("Позиция с таким названием уже есть."); return prisma.cosmetologyInventoryItem.create({ data: { userId, ...input } }); }
export async function createCosmetologyPurchase(userId: string, input: z.infer<typeof purchaseSchema>) { const item = await ownedItem(userId, input.itemId); const amount = decimal(input.totalAmount); const received = decimal(input.quantity); const unitCost = amount.div(received); return prisma.$transaction(async (db) => { const expense = await db.transaction.create({ data: { userId, type: TransactionType.EXPENSE, amount, operationDate: dateFromInput(input.purchaseDate), module: FinanceModule.COSMETOLOGY, description: `Закупка: ${item.name}`, source: "WEB" } }); const lot = await db.cosmetologyInventoryLot.create({ data: { userId, itemId: item.id, initialQuantity: received, availableQuantity: received, totalAmount: amount, unitCost, purchaseDate: dateFromInput(input.purchaseDate), expiryDate: input.expiryDate ? dateFromInput(input.expiryDate) : null, batchNumber: input.batchNumber, comment: input.comment, expenseTransactionId: expense.id } }); await db.cosmetologyInventoryMovement.create({ data: { userId, itemId: item.id, lotId: lot.id, type: "PURCHASE", quantity: received, operationDate: dateFromInput(input.purchaseDate), comment: input.comment } }); await db.cosmetologyInventoryItem.update({ where: { id: item.id }, data: { currentQuantity: { increment: received } } }); return lot; }); }

async function allocateUsage(db: Prisma.TransactionClient, userId: string, itemId: string, quantityValue: Prisma.Decimal, operationDate: Date, visitId: string, comment: string | null) { const item = await db.cosmetologyInventoryItem.findFirst({ where: { id: itemId, userId, deletedAt: null } }); if (!item) throw new Error("Материал недоступен."); if (item.currentQuantity.lt(quantityValue)) throw new Error(`Недостаточно остатка: ${item.name}.`); const lots = await db.cosmetologyInventoryLot.findMany({ where: { userId, itemId, deletedAt: null, availableQuantity: { gt: zero } }, orderBy: [{ expiryDate: "asc" }, { purchaseDate: "asc" }] }); let remaining = quantityValue; let cost = zero; for (const lot of lots) { if (remaining.lte(zero)) break; const used = Prisma.Decimal.min(lot.availableQuantity, remaining); const totalCost = used.mul(lot.unitCost); await db.cosmetologyProcedureMaterialUsage.create({ data: { visitId, itemId, lotId: lot.id, quantity: used, unitCost: lot.unitCost, totalCost } }); await db.cosmetologyInventoryMovement.create({ data: { userId, itemId, lotId: lot.id, visitId, type: "PROCEDURE_USE", quantity: used.neg(), operationDate, comment } }); await db.cosmetologyInventoryLot.update({ where: { id: lot.id }, data: { availableQuantity: { decrement: used } } }); cost = cost.add(totalCost); remaining = remaining.sub(used); }
  if (remaining.gt(zero)) throw new Error("Недостаточно доступных партий материала.");
  await db.cosmetologyInventoryItem.update({ where: { id: itemId }, data: { currentQuantity: { decrement: quantityValue } } }); return cost;
}

async function createVisitUsages(db: Prisma.TransactionClient, userId: string, visitId: string, input: z.infer<typeof visitSchema>, operationDate: Date) { const usages = new Map<string, Prisma.Decimal>(); if (input.itemId && input.usageQuantity) usages.set(input.itemId, decimal(input.usageQuantity)); if (input.procedureTemplateId) { const template = await db.cosmetologyProcedureTemplate.findFirst({ where: { id: input.procedureTemplateId, userId, deletedAt: null }, include: { materials: true } }); if (!template) throw new Error("Шаблон процедуры недоступен."); for (const material of template.materials) usages.set(material.itemId, (usages.get(material.itemId) ?? zero).add(material.quantity)); }
  let cost = zero; for (const [itemId, quantityValue] of usages) cost = cost.add(await allocateUsage(db, userId, itemId, quantityValue, operationDate, visitId, input.comment)); return cost;
}

export async function createCosmetologyVisit(userId: string, input: z.infer<typeof visitSchema>) { return prisma.$transaction(async (db) => { let clientId = input.clientId; if (clientId) await ownedClient(userId, clientId); else { const client = await db.cosmetologyClient.create({ data: { userId, lastName: input.newClientLastName!, firstName: input.newClientFirstName!, phone: input.newClientPhone!, phoneLastFour: phoneLastFour(input.newClientPhone!), contactMethod: "PHONE" } }); clientId = client.id; } const operationDate = dateFromInput(input.operationDate); const income = await db.transaction.create({ data: { userId, type: TransactionType.INCOME, amount: decimal(input.paymentAmount), operationDate, module: FinanceModule.COSMETOLOGY, description: `Процедура: ${input.procedureName}`, source: "WEB" } }); const visit = await db.cosmetologyVisit.create({ data: { userId, clientId: clientId!, procedureTemplateId: input.procedureTemplateId, procedureName: input.procedureName, operationDate, paymentAmount: decimal(input.paymentAmount), comment: input.comment, incomeTransactionId: income.id } }); const costAmount = await createVisitUsages(db, userId, visit.id, input, operationDate); return db.cosmetologyVisit.update({ where: { id: visit.id }, data: { costAmount, profitAmount: decimal(input.paymentAmount).sub(costAmount) } }); }); }
export async function softDeleteCosmetologyVisit(userId: string, id: string) { return prisma.$transaction(async (db) => { const visit = await db.cosmetologyVisit.findFirst({ where: { id, userId, deletedAt: null }, include: { usages: { where: { deletedAt: null } } } }); if (!visit) throw new Error("Визит не найден."); const deletedAt = new Date(); for (const usage of visit.usages) { await db.cosmetologyInventoryLot.update({ where: { id: usage.lotId }, data: { availableQuantity: { increment: usage.quantity } } }); await db.cosmetologyInventoryItem.update({ where: { id: usage.itemId }, data: { currentQuantity: { increment: usage.quantity } } }); } await db.cosmetologyProcedureMaterialUsage.updateMany({ where: { visitId: id, deletedAt: null }, data: { deletedAt } }); await db.cosmetologyInventoryMovement.updateMany({ where: { visitId: id, deletedAt: null }, data: { deletedAt } }); await db.transaction.updateMany({ where: { id: visit.incomeTransactionId, userId, deletedAt: null }, data: { deletedAt } }); return db.cosmetologyVisit.update({ where: { id }, data: { deletedAt } }); }); }

export async function createCosmetologyTemplate(userId: string, input: z.infer<typeof templateSchema>) { return prisma.cosmetologyProcedureTemplate.create({ data: { userId, ...input, basePrice: input.basePrice ? decimal(input.basePrice) : null } }); }
export async function addTemplateMaterial(userId: string, input: z.infer<typeof templateMaterialSchema>) { await ownedItem(userId, input.itemId); const template = await prisma.cosmetologyProcedureTemplate.findFirst({ where: { id: input.templateId, userId, deletedAt: null } }); if (!template) throw new Error("Процедура не найдена."); return prisma.cosmetologyProcedureMaterialTemplate.upsert({ where: { templateId_itemId: { templateId: input.templateId, itemId: input.itemId } }, create: { templateId: input.templateId, itemId: input.itemId, quantity: decimal(input.quantity) }, update: { quantity: decimal(input.quantity) } }); }
export async function createInventoryChange(userId: string, input: z.infer<typeof inventoryChangeSchema>) {
  const item = await ownedItem(userId, input.itemId);
  const quantityValue = decimal(input.quantity);
  if (input.type === "WRITE_OFF" && item.currentQuantity.lt(quantityValue)) throw new Error("Нельзя списать больше остатка.");
  const operationDate = dateFromInput(input.operationDate);
  return prisma.$transaction(async (db) => {
    if (input.type === "WRITE_OFF") {
      const lots = await db.cosmetologyInventoryLot.findMany({ where: { userId, itemId: item.id, deletedAt: null, availableQuantity: { gt: zero } }, orderBy: [{ expiryDate: "asc" }, { purchaseDate: "asc" }] });
      let remaining = quantityValue;
      for (const lot of lots) {
        if (remaining.lte(zero)) break;
        const used = Prisma.Decimal.min(lot.availableQuantity, remaining);
        await db.cosmetologyInventoryLot.update({ where: { id: lot.id }, data: { availableQuantity: { decrement: used } } });
        await db.cosmetologyInventoryMovement.create({ data: { userId, itemId: item.id, lotId: lot.id, type: CosmetologyInventoryMovementType.WRITE_OFF, quantity: used.neg(), operationDate, comment: input.comment } });
        remaining = remaining.sub(used);
      }
      if (remaining.gt(zero)) throw new Error("Недостаточно доступных партий для списания.");
      await db.cosmetologyInventoryItem.update({ where: { id: item.id }, data: { currentQuantity: { decrement: quantityValue } } });
      return { itemId: item.id };
    }
    const lot = await db.cosmetologyInventoryLot.create({ data: { userId, itemId: item.id, initialQuantity: quantityValue, availableQuantity: quantityValue, totalAmount: zero, unitCost: zero, purchaseDate: operationDate, comment: input.comment } });
    const movement = await db.cosmetologyInventoryMovement.create({ data: { userId, itemId: item.id, lotId: lot.id, type: CosmetologyInventoryMovementType.ADJUSTMENT, quantity: quantityValue, operationDate, comment: input.comment } });
    await db.cosmetologyInventoryItem.update({ where: { id: item.id }, data: { currentQuantity: { increment: quantityValue } } });
    return movement;
  });
}

export async function getCosmetologyExpenseCategories(userId: string) { await ensureCategories(userId); return prisma.cosmetologyExpenseCategory.findMany({ where: { userId, isArchived: false }, orderBy: [{ sortOrder: "asc" }, { name: "asc" }] }); }
export async function createCosmetologyExpense(userId: string, input: z.infer<typeof expenseSchema>) { await ensureCategories(userId); let category = input.categoryId ? await prisma.cosmetologyExpenseCategory.findFirst({ where: { id: input.categoryId, userId, isArchived: false } }) : null; if (input.newCategoryName) { const existing = await prisma.cosmetologyExpenseCategory.findFirst({ where: { userId, name: { equals: input.newCategoryName, mode: "insensitive" } } }); category = existing?.isArchived ? await prisma.cosmetologyExpenseCategory.update({ where: { id: existing.id }, data: { isArchived: false } }) : existing ?? await prisma.cosmetologyExpenseCategory.create({ data: { userId, name: input.newCategoryName } }); } if (!category) throw new Error("Категория недоступна."); return prisma.$transaction(async (db) => { const transaction = await db.transaction.create({ data: { userId, type: TransactionType.EXPENSE, amount: decimal(input.amount), operationDate: dateFromInput(input.operationDate), module: FinanceModule.COSMETOLOGY, description: input.description, source: "WEB" } }); return db.cosmetologyExpense.create({ data: { userId, transactionId: transaction.id, categoryId: category!.id, comment: input.comment } }); }); }
export async function createTreatmentPlanItem(userId: string, input: z.infer<typeof planSchema>) { await ownedClient(userId, input.clientId); return prisma.cosmetologyTreatmentPlanItem.create({ data: { userId, ...input, plannedDate: input.plannedDate ? dateFromInput(input.plannedDate) : null } }); }

export async function getCosmetologyClient(userId: string, id: string) { const client = await prisma.cosmetologyClient.findFirst({ where: { id, userId, deletedAt: null }, include: { visits: { where: { deletedAt: null }, include: { usages: { where: { deletedAt: null }, include: { item: true } } }, orderBy: { operationDate: "desc" } }, planItems: { where: { deletedAt: null }, orderBy: { plannedDate: "asc" } } } }); if (!client) throw new Error("Клиент не найден."); const paid = client.visits.reduce((sum, visit) => sum.add(visit.paymentAmount), zero); return { ...client, summary: { visits: client.visits.length, paid: paid.toString(), average: client.visits.length ? paid.div(client.visits.length).toString() : "0.00", lastVisit: client.visits[0]?.operationDate ?? null } }; }
export async function getCosmetologyVisit(userId: string, id: string) { const visit = await prisma.cosmetologyVisit.findFirst({ where: { id, userId, deletedAt: null }, include: { client: true, usages: { where: { deletedAt: null }, include: { item: true, lot: true } }, incomeTransaction: true } }); if (!visit) throw new Error("Визит не найден."); return visit; }
export async function getCosmetologyDashboard(userId: string, period: "TODAY" | "WEEK" | "MONTH" | "YEAR" = "MONTH") { await ensureCategories(userId); const from = periodStart(period, dateFromInput(todayInputValue())); const [items, clients, templates, visits, lots, expenses, categories] = await Promise.all([prisma.cosmetologyInventoryItem.findMany({ where: { userId, deletedAt: null }, include: { lots: { where: { deletedAt: null } } }, orderBy: { name: "asc" } }), prisma.cosmetologyClient.findMany({ where: { userId, deletedAt: null }, orderBy: [{ lastName: "asc" }, { firstName: "asc" }] }), prisma.cosmetologyProcedureTemplate.findMany({ where: { userId, deletedAt: null, isArchived: false }, include: { materials: { include: { item: true } } }, orderBy: { name: "asc" } }), prisma.cosmetologyVisit.findMany({ where: { userId, deletedAt: null, operationDate: { gte: from }, incomeTransaction: { deletedAt: null } }, include: { client: true, procedureTemplate: true, usages: { where: { deletedAt: null }, include: { item: true } }, incomeTransaction: true }, orderBy: { operationDate: "desc" } }), prisma.cosmetologyInventoryLot.findMany({ where: { userId, deletedAt: null }, include: { item: true }, orderBy: { purchaseDate: "desc" } }), prisma.cosmetologyExpense.findMany({ where: { userId, deletedAt: null, transaction: { deletedAt: null, operationDate: { gte: from } } }, include: { transaction: true, category: true }, orderBy: { transaction: { operationDate: "desc" } } }), getCosmetologyExpenseCategories(userId)]); const income = visits.reduce((sum, visit) => sum.add(visit.paymentAmount), zero); const cost = visits.reduce((sum, visit) => sum.add(visit.costAmount), zero); const operationalExpense = expenses.reduce((sum, expense) => sum.add(expense.transaction.amount), zero); const purchaseExpense = lots.filter((lot) => lot.purchaseDate >= from).reduce((sum, lot) => sum.add(lot.totalAmount), zero); return { items, clients, templates, visits, lots, expenses, categories, report: { income: income.toString(), cost: cost.toString(), operationalExpense: operationalExpense.toString(), cashExpense: purchaseExpense.add(operationalExpense).toString(), procedureProfit: income.sub(cost).toString(), result: income.sub(cost).sub(operationalExpense).toString() } }; }
