import "server-only";

import { CosmetologyClientStatus, CosmetologyContactMethod, CosmetologyInventoryMovementType, CosmetologyPlanStatus, CosmetologyUnit, CosmetologyVisitStatus, CosmetologyWallet, CosmetologyWalletMovementType, FinanceModule, Prisma, TransactionType } from "@prisma/client";
import { z } from "zod";

import { periodStart } from "@/features/family/calculations";
import { dateFromInput, todayInputValue } from "@/lib/dates";
import { prisma } from "@/lib/prisma";

const money = z.string().trim().regex(/^\d+(?:[.,]\d{1,2})?$/);
const quantity = z.string().trim().regex(/^\d+(?:[.,]\d{1,3})?$/).refine((value) => new Prisma.Decimal(value.replace(",", ".")).gt(0));
const nonNegativeMoney = z.string().trim().regex(/^\d+(?:[.,]\d{1,2})?$/);
const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const optional = z.string().trim().max(500).nullable();
const decimal = (value: string) => new Prisma.Decimal(value.replace(",", "."));
const zero = new Prisma.Decimal(0);

export const cosmeticItemCategories = ["Ботулотоксин", "Филлер", "Биоревитализант", "Мезопрепарат", "PDRN", "Полимолочная кислота", "Коллагеновый стимулятор", "Шприцы", "Иглы", "Канюли", "Перчатки", "Салфетки", "Физраствор", "Прочее"];
export const cosmeticExpenseCategories = ["Аренда кабинета / салона", "Реклама", "Обучение", "Оборудование", "Мебель", "Хозяйственные расходы", "Интернет / связь", "Поездки", "Проживание", "Транспорт", "Прочее"];
export const procedureCategories = ["Ботулинотерапия", "Контурная пластика", "Мезотерапия", "Биоревитализация", "Коллагеностимуляция", "Массаж", "Консультация", "Другое"];
export const clientSources = ["Instagram", "TikTok", "Facebook", "Google", "Сайт", "По рекомендации", "Другое"];
export const clientMarks = ["Тяжёлый клиент", "Очень лояльный", "Высокий средний чек", "Любит акции", "Часто переносит запись", "Часто опаздывает", "Пришёл по рекомендации"];

export const clientSchema = z.object({ lastName: z.string().trim().min(1).max(80), firstName: z.string().trim().min(1).max(80), phone: z.string().trim().min(5).max(40), birthDate: date.nullable(), contactMethod: z.nativeEnum(CosmetologyContactMethod), contactValue: z.string().trim().max(300).nullable(), source: z.string().trim().max(80).nullable(), referrerId: z.string().cuid().nullable(), status: z.nativeEnum(CosmetologyClientStatus), specialMarks: z.array(z.string().trim().min(1).max(80)).max(12), notes: optional, allergies: optional, contraindications: optional, medicalNotes: optional });
export const itemSchema = z.object({ name: z.string().trim().min(1).max(120), category: z.string().trim().min(1).max(80), brand: z.string().trim().max(80).nullable(), unit: z.nativeEnum(CosmetologyUnit), minimumQuantity: z.string().trim().regex(/^\d+(?:[.,]\d{1,3})?$/), comment: optional });
export const purchaseSchema = z.object({ itemId: z.string().cuid(), quantity, totalAmount: money, purchaseDate: date, supplier: z.string().trim().max(120).nullable(), wallet: z.nativeEnum(CosmetologyWallet), expiryDate: date.nullable(), batchNumber: z.string().trim().max(120).nullable(), comment: optional });
export const inventoryChangeSchema = z.object({ itemId: z.string().cuid(), quantity, operationDate: date, type: z.enum(["WRITE_OFF", "ADJUSTMENT"]), comment: z.string().trim().min(1).max(500) });
export const templateSchema = z.object({ name: z.string().trim().min(1).max(120), category: z.string().trim().min(1).max(80), basePrice: money.nullable(), durationMinutes: z.coerce.number().int().positive().nullable(), comment: optional });
export const templateMaterialSchema = z.object({ templateId: z.string().cuid(), itemId: z.string().cuid(), quantity });
const walletAmounts = z.object({ cashAmount: nonNegativeMoney.nullable(), monoAmount: nonNegativeMoney.nullable(), privatAmount: nonNegativeMoney.nullable() });
export const appointmentSchema = z.object({ clientId: z.string().cuid().nullable(), clientName: z.string().trim().max(160).nullable(), phone: z.string().trim().max(40).nullable(), contactValue: z.string().trim().max(300).nullable(), procedureTemplateId: z.string().cuid().nullable(), procedureName: z.string().trim().max(120).nullable(), plannedAmount: nonNegativeMoney.nullable(), operationDate: date, scheduledTime: z.string().regex(/^([01]\d|2[0-3]):[0-5]\d$/).nullable(), durationMinutes: z.coerce.number().int().min(15).max(720).multipleOf(15).nullable(), comment: optional }).merge(walletAmounts).superRefine((value, ctx) => { if (!value.clientId && !value.clientName) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["clientName"], message: "Введите имя или выберите клиента." }); if (!value.procedureTemplateId && !value.procedureName) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["procedureName"], message: "Выберите или введите услугу." }); });
export const completeVisitSchema = z.object({ id: z.string().cuid(), procedureTemplateIds: z.array(z.string().cuid()).max(8), procedureName: z.string().trim().max(120).nullable(), paymentAmount: nonNegativeMoney, operationDate: date, itemId: z.string().cuid().nullable(), usageQuantity: quantity.nullable(), comment: optional }).merge(walletAmounts).superRefine((value, ctx) => { if (Boolean(value.itemId) !== Boolean(value.usageQuantity)) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["itemId"], message: "Укажите и материал, и количество." }); if (!value.procedureTemplateIds.length && !value.procedureName) ctx.addIssue({ code: z.ZodIssueCode.custom, path: ["procedureName"], message: "Выберите услугу или укажите её вручную." }); });
export const expenseSchema = z.object({ categoryId: z.string().cuid().nullable(), newCategoryName: z.string().trim().min(1).max(80).nullable(), amount: money, wallet: z.nativeEnum(CosmetologyWallet), operationDate: date, description: z.string().trim().min(1).max(500), comment: optional }).refine((value) => Boolean(value.categoryId || value.newCategoryName), { path: ["categoryId"], message: "Выберите категорию." });
export const planSchema = z.object({ clientId: z.string().cuid(), title: z.string().trim().min(1).max(160), plannedDate: date.nullable(), status: z.nativeEnum(CosmetologyPlanStatus), note: optional });
export const formValue = (formData: FormData, name: string) => { const value = formData.get(name); return typeof value === "string" && value.trim() ? value.trim() : null; };

function phoneLastFour(phone: string) { const digits = phone.replace(/\D/g, ""); if (digits.length < 4) throw new Error("Введите корректный номер телефона."); return digits.slice(-4); }
function amounts(input: z.infer<typeof walletAmounts>) { return [{ wallet: CosmetologyWallet.CASH, amount: decimal(input.cashAmount ?? "0") }, { wallet: CosmetologyWallet.MONO, amount: decimal(input.monoAmount ?? "0") }, { wallet: CosmetologyWallet.PRIVAT, amount: decimal(input.privatAmount ?? "0") }].filter((item) => item.amount.gt(zero)); }
async function recordWalletIncome(db: Prisma.TransactionClient, userId: string, visitId: string, operationDate: Date, items: ReturnType<typeof amounts>, type: CosmetologyWalletMovementType, description: string) { let firstTransactionId: string | null = null; for (const item of items) { const transaction = await db.transaction.create({ data: { userId, type: TransactionType.INCOME, amount: item.amount, operationDate, module: FinanceModule.COSMETOLOGY, description, source: "WEB" } }); await db.cosmetologyWalletMovement.create({ data: { userId, visitId, wallet: item.wallet, type, amount: item.amount, operationDate, description, transactionId: transaction.id } }); firstTransactionId ??= transaction.id; } return firstTransactionId; }
async function ownedClient(userId: string, id: string) { const client = await prisma.cosmetologyClient.findFirst({ where: { id, userId, deletedAt: null } }); if (!client) throw new Error("Клиент не найден."); return client; }
async function ownedItem(userId: string, id: string) { const item = await prisma.cosmetologyInventoryItem.findFirst({ where: { id, userId, deletedAt: null } }); if (!item) throw new Error("Препарат или расходник не найден."); return item; }
async function ensureCategories(userId: string) { if (!await prisma.cosmetologyExpenseCategory.count({ where: { userId } })) await prisma.cosmetologyExpenseCategory.createMany({ data: cosmeticExpenseCategories.map((name, sortOrder) => ({ userId, name, sortOrder })), skipDuplicates: true }); }

export async function createCosmetologyClient(userId: string, input: z.infer<typeof clientSchema>) { if (input.referrerId) await ownedClient(userId, input.referrerId); return prisma.cosmetologyClient.create({ data: { userId, ...input, displayName: `${input.firstName} ${input.lastName}`.trim(), phoneLastFour: phoneLastFour(input.phone), birthDate: input.birthDate ? dateFromInput(input.birthDate) : null } }); }
export async function updateCosmetologyClient(userId: string, id: string, input: z.infer<typeof clientSchema>) { await ownedClient(userId, id); if (input.referrerId) await ownedClient(userId, input.referrerId); if (input.referrerId === id) throw new Error("Клиент не может рекомендовать сам себя."); return prisma.cosmetologyClient.update({ where: { id }, data: { ...input, displayName: `${input.firstName} ${input.lastName}`.trim(), phoneLastFour: phoneLastFour(input.phone), birthDate: input.birthDate ? dateFromInput(input.birthDate) : null } }); }
export async function getCosmetologyClients(userId: string, query = "") { return prisma.cosmetologyClient.findMany({ where: { userId, deletedAt: null, ...(query ? { OR: [{ displayName: { contains: query, mode: "insensitive" } }, { lastName: { contains: query, mode: "insensitive" } }, { firstName: { contains: query, mode: "insensitive" } }, { phone: { contains: query } }, { contactValue: { contains: query, mode: "insensitive" } }, { phoneLastFour: { equals: query.replace(/\D/g, "").slice(-4) } }] } : {}) }, orderBy: [{ displayName: "asc" }, { lastName: "asc" }] }); }

export async function createCosmetologyItem(userId: string, input: z.infer<typeof itemSchema>) { const exists = await prisma.cosmetologyInventoryItem.findFirst({ where: { userId, name: { equals: input.name, mode: "insensitive" }, deletedAt: null } }); if (exists) throw new Error("Позиция с таким названием уже есть."); return prisma.cosmetologyInventoryItem.create({ data: { userId, ...input, minimumQuantity: decimal(input.minimumQuantity) } }); }
export async function createCosmetologyPurchase(userId: string, input: z.infer<typeof purchaseSchema>) { const item = await ownedItem(userId, input.itemId); const amount = decimal(input.totalAmount); const received = decimal(input.quantity); const unitCost = amount.div(received); const operationDate = dateFromInput(input.purchaseDate); return prisma.$transaction(async (db) => { const expense = await db.transaction.create({ data: { userId, type: TransactionType.EXPENSE, amount, operationDate, module: FinanceModule.COSMETOLOGY, description: `Закупка: ${item.name}`, source: "WEB" } }); const lot = await db.cosmetologyInventoryLot.create({ data: { userId, itemId: item.id, initialQuantity: received, availableQuantity: received, totalAmount: amount, unitCost, purchaseDate: operationDate, expiryDate: input.expiryDate ? dateFromInput(input.expiryDate) : null, batchNumber: input.batchNumber, supplier: input.supplier, comment: input.comment, expenseTransactionId: expense.id } }); await db.cosmetologyWalletMovement.create({ data: { userId, wallet: input.wallet, type: CosmetologyWalletMovementType.PURCHASE, amount: amount.neg(), operationDate, description: `Закупка: ${item.name}`, transactionId: expense.id } }); await db.cosmetologyInventoryMovement.create({ data: { userId, itemId: item.id, lotId: lot.id, type: "PURCHASE", quantity: received, operationDate, comment: input.comment } }); await db.cosmetologyInventoryItem.update({ where: { id: item.id }, data: { currentQuantity: { increment: received } } }); return lot; }); }

async function allocateUsage(db: Prisma.TransactionClient, userId: string, itemId: string, quantityValue: Prisma.Decimal, operationDate: Date, visitId: string, comment: string | null) { const item = await db.cosmetologyInventoryItem.findFirst({ where: { id: itemId, userId, deletedAt: null } }); if (!item) throw new Error("Материал недоступен."); if (item.currentQuantity.lt(quantityValue)) throw new Error(`Недостаточно остатка: ${item.name}.`); const lots = await db.cosmetologyInventoryLot.findMany({ where: { userId, itemId, deletedAt: null, availableQuantity: { gt: zero } }, orderBy: [{ expiryDate: "asc" }, { purchaseDate: "asc" }] }); let remaining = quantityValue; let cost = zero; for (const lot of lots) { if (remaining.lte(zero)) break; const used = Prisma.Decimal.min(lot.availableQuantity, remaining); const totalCost = used.mul(lot.unitCost); await db.cosmetologyProcedureMaterialUsage.create({ data: { visitId, itemId, lotId: lot.id, quantity: used, unitCost: lot.unitCost, totalCost } }); await db.cosmetologyInventoryMovement.create({ data: { userId, itemId, lotId: lot.id, visitId, type: "PROCEDURE_USE", quantity: used.neg(), operationDate, comment } }); await db.cosmetologyInventoryLot.update({ where: { id: lot.id }, data: { availableQuantity: { decrement: used } } }); cost = cost.add(totalCost); remaining = remaining.sub(used); }
  if (remaining.gt(zero)) throw new Error("Недостаточно доступных партий материала.");
  await db.cosmetologyInventoryItem.update({ where: { id: itemId }, data: { currentQuantity: { decrement: quantityValue } } }); return cost;
}

async function createVisitUsages(db: Prisma.TransactionClient, userId: string, visitId: string, input: z.infer<typeof completeVisitSchema>, operationDate: Date) { const usages = new Map<string, Prisma.Decimal>(); if (input.itemId && input.usageQuantity) usages.set(input.itemId, decimal(input.usageQuantity)); const templateIds = [...new Set(input.procedureTemplateIds)]; const templates = templateIds.length ? await db.cosmetologyProcedureTemplate.findMany({ where: { id: { in: templateIds }, userId, deletedAt: null }, include: { materials: true } }) : []; if (templates.length !== templateIds.length) throw new Error("Одна из техкарт недоступна."); for (const template of templates) for (const material of template.materials) usages.set(material.itemId, (usages.get(material.itemId) ?? zero).add(material.quantity));
  let cost = zero; for (const [itemId, quantityValue] of usages) cost = cost.add(await allocateUsage(db, userId, itemId, quantityValue, operationDate, visitId, input.comment)); return { cost, templates: templateIds.map((id) => templates.find((template) => template.id === id)!) };
}

export async function createCosmetologyAppointment(userId: string, input: z.infer<typeof appointmentSchema>) { return prisma.$transaction(async (db) => { let clientId = input.clientId; if (clientId) await ownedClient(userId, clientId); else { const existing = await db.cosmetologyClient.findFirst({ where: { userId, deletedAt: null, displayName: { equals: input.clientName!, mode: "insensitive" } } }); if (existing) clientId = existing.id; else { const parts = input.clientName!.split(/\s+/); const firstName = parts.shift()!; const lastName = parts.join(" ") || "Клиент"; const client = await db.cosmetologyClient.create({ data: { userId, firstName, lastName, displayName: input.clientName, phone: input.phone || "Не указан", phoneLastFour: input.phone ? phoneLastFour(input.phone) : "0000", contactMethod: input.contactValue ? "INSTAGRAM" : "PHONE", contactValue: input.contactValue } }); clientId = client.id; } } const template = input.procedureTemplateId ? await db.cosmetologyProcedureTemplate.findFirst({ where: { id: input.procedureTemplateId, userId, deletedAt: null } }) : null; if (input.procedureTemplateId && !template) throw new Error("Услуга недоступна."); const plannedAmount = input.plannedAmount ? decimal(input.plannedAmount) : template?.basePrice ?? null; const operationDate = dateFromInput(input.operationDate); const visit = await db.cosmetologyVisit.create({ data: { userId, clientId: clientId!, procedureTemplateId: input.procedureTemplateId, procedureName: template?.name ?? input.procedureName!, operationDate, scheduledTime: input.scheduledTime, durationMinutes: input.durationMinutes, plannedAmount, paymentAmount: zero, status: CosmetologyVisitStatus.SCHEDULED, comment: input.comment } }); const prepayment = amounts(input); if (prepayment.length) { const transactionId = await recordWalletIncome(db, userId, visit.id, operationDate, prepayment, CosmetologyWalletMovementType.PREPAYMENT, `Предоплата: ${visit.procedureName}`); const paidAmount = prepayment.reduce((sum, item) => sum.add(item.amount), zero); return db.cosmetologyVisit.update({ where: { id: visit.id }, data: { paidAmount, incomeTransactionId: transactionId } }); } return visit; }); }
export async function completeCosmetologyVisit(userId: string, input: z.infer<typeof completeVisitSchema>) { return prisma.$transaction(async (db) => { const visit = await db.cosmetologyVisit.findFirst({ where: { id: input.id, userId, deletedAt: null, status: CosmetologyVisitStatus.SCHEDULED } }); if (!visit) throw new Error("Закрыть можно только активную запись."); const operationDate = dateFromInput(input.operationDate); const finalAmount = decimal(input.paymentAmount); const received = amounts(input); const newlyPaid = received.reduce((sum, item) => sum.add(item.amount), zero); if (visit.paidAmount.add(newlyPaid).gt(finalAmount)) throw new Error("Оплата не может быть больше итоговой суммы. Сначала оформите возврат предоплаты."); const usageResult = await createVisitUsages(db, userId, visit.id, input, operationDate); const names = [...usageResult.templates.map((template) => template.name), input.procedureName].filter((name): name is string => Boolean(name)).filter((name, index, all) => all.findIndex((item) => item.toLocaleLowerCase("ru-RU") === name.toLocaleLowerCase("ru-RU")) === index); const procedureName = names.join(" + "); const transactionId = await recordWalletIncome(db, userId, visit.id, operationDate, received, CosmetologyWalletMovementType.SETTLEMENT, `Оплата процедуры: ${procedureName}`); return db.cosmetologyVisit.update({ where: { id: visit.id }, data: { procedureTemplateId: usageResult.templates[0]?.id ?? null, procedureName, operationDate, paymentAmount: finalAmount, paidAmount: visit.paidAmount.add(newlyPaid), comment: input.comment, incomeTransactionId: visit.incomeTransactionId ?? transactionId, costAmount: usageResult.cost, profitAmount: finalAmount.sub(usageResult.cost), status: CosmetologyVisitStatus.COMPLETED } }); }); }
export async function softDeleteCosmetologyVisit(userId: string, id: string) { return prisma.$transaction(async (db) => { const visit = await db.cosmetologyVisit.findFirst({ where: { id, userId, deletedAt: null }, include: { usages: { where: { deletedAt: null } }, walletMovements: { where: { deletedAt: null } } } }); if (!visit) throw new Error("Запись не найдена."); const deletedAt = new Date(); for (const usage of visit.usages) { await db.cosmetologyInventoryLot.update({ where: { id: usage.lotId }, data: { availableQuantity: { increment: usage.quantity } } }); await db.cosmetologyInventoryItem.update({ where: { id: usage.itemId }, data: { currentQuantity: { increment: usage.quantity } } }); } await db.cosmetologyProcedureMaterialUsage.updateMany({ where: { visitId: id, deletedAt: null }, data: { deletedAt } }); await db.cosmetologyInventoryMovement.updateMany({ where: { visitId: id, deletedAt: null }, data: { deletedAt } }); await db.cosmetologyWalletMovement.updateMany({ where: { visitId: id, deletedAt: null }, data: { deletedAt } }); const transactionIds = visit.walletMovements.map((item) => item.transactionId).filter((item): item is string => Boolean(item)); if (transactionIds.length) await db.transaction.updateMany({ where: { id: { in: transactionIds }, userId, deletedAt: null }, data: { deletedAt } }); return db.cosmetologyVisit.update({ where: { id }, data: { deletedAt, status: CosmetologyVisitStatus.CANCELLED } }); }); }

export async function createCosmetologyTemplate(userId: string, input: z.infer<typeof templateSchema>) { return prisma.cosmetologyProcedureTemplate.create({ data: { userId, ...input, basePrice: input.basePrice ? decimal(input.basePrice) : null } }); }
export async function addTemplateMaterial(userId: string, input: z.infer<typeof templateMaterialSchema>) { await ownedItem(userId, input.itemId); const template = await prisma.cosmetologyProcedureTemplate.findFirst({ where: { id: input.templateId, userId, deletedAt: null } }); if (!template) throw new Error("Процедура не найдена."); return prisma.cosmetologyProcedureMaterialTemplate.upsert({ where: { templateId_itemId: { templateId: input.templateId, itemId: input.itemId } }, create: { templateId: input.templateId, itemId: input.itemId, quantity: decimal(input.quantity) }, update: { quantity: decimal(input.quantity) } }); }
export async function createInventoryChange(userId: string, input: z.infer<typeof inventoryChangeSchema>) {
  const item = await ownedItem(userId, input.itemId);
  const quantityValue = decimal(input.quantity);
  if (input.type === "WRITE_OFF" && item.currentQuantity.lt(quantityValue)) throw new Error("Нельзя списать больше остатка.");
  const operationDate = dateFromInput(input.operationDate);
  return prisma.$transaction(async (db) => {
    if (input.type === "WRITE_OFF") {
      const lots = await db.cosmetologyInventoryLot.findMany({ where: { userId, itemId: item.id, deletedAt: null, availableQuantity: { gt: zero } }, orderBy: [{ expiryDate: "asc" }, { purchaseDate: "asc" }] });
      let remaining = quantityValue;
      for (const lot of lots) {
        if (remaining.lte(zero)) break;
        const used = Prisma.Decimal.min(lot.availableQuantity, remaining);
        await db.cosmetologyInventoryLot.update({ where: { id: lot.id }, data: { availableQuantity: { decrement: used } } });
        await db.cosmetologyInventoryMovement.create({ data: { userId, itemId: item.id, lotId: lot.id, type: CosmetologyInventoryMovementType.WRITE_OFF, quantity: used.neg(), operationDate, comment: input.comment } });
        remaining = remaining.sub(used);
      }
      if (remaining.gt(zero)) throw new Error("Недостаточно доступных партий для списания.");
      await db.cosmetologyInventoryItem.update({ where: { id: item.id }, data: { currentQuantity: { decrement: quantityValue } } });
      return { itemId: item.id };
    }
    const lot = await db.cosmetologyInventoryLot.create({ data: { userId, itemId: item.id, initialQuantity: quantityValue, availableQuantity: quantityValue, totalAmount: zero, unitCost: zero, purchaseDate: operationDate, comment: input.comment } });
    const movement = await db.cosmetologyInventoryMovement.create({ data: { userId, itemId: item.id, lotId: lot.id, type: CosmetologyInventoryMovementType.ADJUSTMENT, quantity: quantityValue, operationDate, comment: input.comment } });
    await db.cosmetologyInventoryItem.update({ where: { id: item.id }, data: { currentQuantity: { increment: quantityValue } } });
    return movement;
  });
}

export async function getCosmetologyExpenseCategories(userId: string) { await ensureCategories(userId); return prisma.cosmetologyExpenseCategory.findMany({ where: { userId, isArchived: false }, orderBy: [{ sortOrder: "asc" }, { name: "asc" }] }); }
export async function createCosmetologyExpense(userId: string, input: z.infer<typeof expenseSchema>) { await ensureCategories(userId); let category = input.categoryId ? await prisma.cosmetologyExpenseCategory.findFirst({ where: { id: input.categoryId, userId, isArchived: false } }) : null; if (input.newCategoryName) { const existing = await prisma.cosmetologyExpenseCategory.findFirst({ where: { userId, name: { equals: input.newCategoryName, mode: "insensitive" } } }); category = existing?.isArchived ? await prisma.cosmetologyExpenseCategory.update({ where: { id: existing.id }, data: { isArchived: false } }) : existing ?? await prisma.cosmetologyExpenseCategory.create({ data: { userId, name: input.newCategoryName } }); } if (!category) throw new Error("Категория недоступна."); return prisma.$transaction(async (db) => { const amount = decimal(input.amount); const operationDate = dateFromInput(input.operationDate); const transaction = await db.transaction.create({ data: { userId, type: TransactionType.EXPENSE, amount, operationDate, module: FinanceModule.COSMETOLOGY, description: input.description, source: "WEB" } }); await db.cosmetologyWalletMovement.create({ data: { userId, wallet: input.wallet, type: CosmetologyWalletMovementType.EXPENSE, amount: amount.neg(), operationDate, description: input.description, transactionId: transaction.id } }); return db.cosmetologyExpense.create({ data: { userId, transactionId: transaction.id, categoryId: category!.id, comment: input.comment } }); }); }
export async function createTreatmentPlanItem(userId: string, input: z.infer<typeof planSchema>) { await ownedClient(userId, input.clientId); return prisma.cosmetologyTreatmentPlanItem.create({ data: { userId, ...input, plannedDate: input.plannedDate ? dateFromInput(input.plannedDate) : null } }); }

export async function getCosmetologyClient(userId: string, id: string) { const client = await prisma.cosmetologyClient.findFirst({ where: { id, userId, deletedAt: null }, include: { visits: { where: { deletedAt: null }, include: { usages: { where: { deletedAt: null }, include: { item: true } } }, orderBy: { operationDate: "desc" } }, planItems: { where: { deletedAt: null }, orderBy: { plannedDate: "asc" } } } }); if (!client) throw new Error("Клиент не найден."); const paid = client.visits.reduce((sum, visit) => sum.add(visit.paymentAmount), zero); return { ...client, summary: { visits: client.visits.length, paid: paid.toString(), average: client.visits.length ? paid.div(client.visits.length).toString() : "0.00", lastVisit: client.visits[0]?.operationDate ?? null } }; }
export async function getCosmetologyVisit(userId: string, id: string) { const visit = await prisma.cosmetologyVisit.findFirst({ where: { id, userId, deletedAt: null }, include: { client: true, usages: { where: { deletedAt: null }, include: { item: true, lot: true } }, incomeTransaction: true } }); if (!visit) throw new Error("Визит не найден."); return visit; }
export async function getCosmetologyAppointments(userId: string) { return prisma.cosmetologyVisit.findMany({ where: { userId, deletedAt: null }, include: { client: true, procedureTemplate: true }, orderBy: [{ operationDate: "asc" }, { scheduledTime: "asc" }] }); }
export async function getCosmetologyOperations(userId: string) { const [appointments, movements, items] = await Promise.all([getCosmetologyAppointments(userId), prisma.cosmetologyWalletMovement.findMany({ where: { userId, deletedAt: null }, select: { wallet: true, amount: true } }), prisma.cosmetologyInventoryItem.findMany({ where: { userId, deletedAt: null }, orderBy: { name: "asc" } })]); const balances = Object.fromEntries(Object.values(CosmetologyWallet).map((wallet) => [wallet, "0.00"])) as Record<CosmetologyWallet, string>; for (const movement of movements) balances[movement.wallet] = new Prisma.Decimal(balances[movement.wallet]).add(movement.amount).toFixed(2); const debts = appointments.filter((item) => item.status === CosmetologyVisitStatus.COMPLETED && item.paymentAmount.gt(item.paidAmount)); return { appointments, balances, debts, lowStock: items.filter((item) => item.currentQuantity.lte(item.minimumQuantity)) }; }
export async function getCosmetologyDashboard(userId: string, period: "TODAY" | "WEEK" | "MONTH" | "YEAR" = "MONTH") { await ensureCategories(userId); const from = periodStart(period, dateFromInput(todayInputValue())); const [items, clients, templates, visits, lots, expenses, categories] = await Promise.all([prisma.cosmetologyInventoryItem.findMany({ where: { userId, deletedAt: null }, include: { lots: { where: { deletedAt: null } } }, orderBy: { name: "asc" } }), prisma.cosmetologyClient.findMany({ where: { userId, deletedAt: null }, orderBy: [{ lastName: "asc" }, { firstName: "asc" }] }), prisma.cosmetologyProcedureTemplate.findMany({ where: { userId, deletedAt: null, isArchived: false }, include: { materials: { include: { item: true } } }, orderBy: { name: "asc" } }), prisma.cosmetologyVisit.findMany({ where: { userId, deletedAt: null, operationDate: { gte: from }, incomeTransaction: { deletedAt: null } }, include: { client: true, procedureTemplate: true, usages: { where: { deletedAt: null }, include: { item: true } }, incomeTransaction: true }, orderBy: { operationDate: "desc" } }), prisma.cosmetologyInventoryLot.findMany({ where: { userId, deletedAt: null }, include: { item: true }, orderBy: { purchaseDate: "desc" } }), prisma.cosmetologyExpense.findMany({ where: { userId, deletedAt: null, transaction: { deletedAt: null, operationDate: { gte: from } } }, include: { transaction: true, category: true }, orderBy: { transaction: { operationDate: "desc" } } }), getCosmetologyExpenseCategories(userId)]); const income = visits.reduce((sum, visit) => sum.add(visit.paymentAmount), zero); const cost = visits.reduce((sum, visit) => sum.add(visit.costAmount), zero); const operationalExpense = expenses.reduce((sum, expense) => sum.add(expense.transaction.amount), zero); const purchaseExpense = lots.filter((lot) => lot.purchaseDate >= from).reduce((sum, lot) => sum.add(lot.totalAmount), zero); return { items, clients, templates, visits, lots, expenses, categories, report: { income: income.toString(), cost: cost.toString(), operationalExpense: operationalExpense.toString(), cashExpense: purchaseExpense.add(operationalExpense).toString(), procedureProfit: income.sub(cost).toString(), result: income.sub(cost).sub(operationalExpense).toString() } }; }
