import "server-only";

import { FinanceModule, Prisma, PoultryBatchSource } from "@prisma/client";
import { z } from "zod";

import { dateFromInput, todayInputValue } from "@/lib/dates";
import { prisma } from "@/lib/prisma";
import { hatchRate, poultryAgeDays, poultryReport, remainingBags, remainingQuantity, saleTotal } from "@/features/poultry/calculations";
import { periodStart } from "@/features/family/calculations";

const money = z.string().trim().regex(/^\d+(?:[.,]\d{1,3})?$/);
const positiveInt = z.coerce.number().int().positive();
const date = z.string().regex(/^\d{4}-\d{2}-\d{2}$/);
const optional = (value: FormDataEntryValue | null) => typeof value === "string" && value.trim() ? value.trim() : null;
const decimal = (value: string) => new Prisma.Decimal(value.replace(",", "."));

export const batchSchema = z.object({ name: z.string().trim().min(1).max(120), birdType: z.string().trim().min(1).max(80), breed: z.string().trim().max(80).nullable(), startDate: date, quantity: positiveInt, source: z.nativeEnum(PoultryBatchSource), comment: z.string().trim().max(500).nullable() });
export const movementSchema = z.object({ batchId: z.string().cuid(), type: z.enum(["ADD", "MORTALITY", "FAMILY_USE", "TRANSFER", "ADJUSTMENT"]), quantity: positiveInt, operationDate: date, comment: z.string().trim().max(500).nullable() });
export const saleSchema = z.object({ batchId: z.string().cuid().nullable(), buyer: z.string().trim().max(120).nullable(), itemName: z.string().trim().min(1).max(120), quantity: z.coerce.number().int().positive().nullable(), weightKg: money.nullable(), price: money.nullable(), totalAmount: money.nullable(), operationDate: date, comment: z.string().trim().max(500).nullable() }).refine((data) => data.quantity || data.weightKg, "Вкажіть кількість або вагу.");
export const feedPurchaseSchema = z.object({ name: z.string().trim().min(1).max(120), type: z.string().trim().max(80).nullable(), bagSizeKg: money.nullable(), bags: positiveInt, totalAmount: money, operationDate: date, comment: z.string().trim().max(500).nullable() });
export const feedUsageSchema = z.object({ lotId: z.string().cuid(), batchId: z.string().cuid(), bags: positiveInt, operationDate: date, comment: z.string().trim().max(500).nullable() });
export const incubationSchema = z.object({ name: z.string().trim().min(1).max(120), birdType: z.string().trim().min(1).max(80), setDate: date, comment: z.string().trim().max(500).nullable(), items: z.array(z.object({ breed: z.string().trim().min(1).max(80), setQuantity: positiveInt, comment: z.string().trim().max(500).nullable() })).min(1).max(8) });
export const incubationUpdateSchema = z.object({ itemId: z.string().cuid(), infertileQuantity: z.coerce.number().int().min(0), lossQuantity: z.coerce.number().int().min(0), hatchedQuantity: z.coerce.number().int().min(0) });
export const operationalExpenseSchema = z.object({ categoryId: z.string().cuid(), batchId: z.string().cuid().nullable(), amount: money, operationDate: date, description: z.string().trim().min(1).max(500) });

async function poultryCategory(userId: string, id: string, kind: "INCOME" | "EXPENSE") {
  const category = await prisma.category.findFirst({ where: { id, module: FinanceModule.POULTRY, isArchived: false, OR: [{ userId }, { userId: null }] } });
  if (!category || (category.kind !== kind && category.kind !== "BOTH")) throw new Error("Оберіть доступну категорію Птахівництва.");
  return category;
}
async function categoryByName(userId: string, name: string, kind: "INCOME" | "EXPENSE") { const category = await prisma.category.findFirst({ where: { name, module: FinanceModule.POULTRY, isArchived: false, OR: [{ userId }, { userId: null }] } }); if (!category) throw new Error("Системна категорія Птахівництва відсутня."); return poultryCategory(userId, category.id, kind); }

export async function getPoultryCategories(userId: string) { return prisma.category.findMany({ where: { module: FinanceModule.POULTRY, isArchived: false, OR: [{ userId }, { userId: null }] }, orderBy: [{ sortOrder: "asc" }, { name: "asc" }] }); }
export async function createPoultryBatch(userId: string, input: z.infer<typeof batchSchema>) { return prisma.poultryBatch.create({ data: { userId, name: input.name, birdType: input.birdType, breed: input.breed, startDate: dateFromInput(input.startDate), startingQuantity: input.quantity, currentQuantity: input.quantity, source: input.source, comment: input.comment } }); }
export async function createPoultryMovement(userId: string, input: z.infer<typeof movementSchema>) { return prisma.$transaction(async (db) => { const batch = await db.poultryBatch.findFirst({ where: { id: input.batchId, userId, status: "ACTIVE", deletedAt: null } }); if (!batch) throw new Error("Активну партію не знайдено."); const currentQuantity = remainingQuantity(batch.currentQuantity, input.type, input.quantity); const movement = await db.poultryMovement.create({ data: { userId, batchId: batch.id, type: input.type, quantity: input.quantity, operationDate: dateFromInput(input.operationDate), comment: input.comment } }); await db.poultryBatch.update({ where: { id: batch.id }, data: { currentQuantity } }); return movement; }); }
export async function createPoultrySale(userId: string, input: z.infer<typeof saleSchema>) { const totalAmount = saleTotal(input.quantity, input.weightKg, input.price, input.totalAmount); const category = await categoryByName(userId, "Продаж продукції", "INCOME"); return prisma.$transaction(async (db) => { let batch = null; if (input.batchId) { batch = await db.poultryBatch.findFirst({ where: { id: input.batchId, userId, status: "ACTIVE", deletedAt: null } }); if (!batch) throw new Error("Активну партію не знайдено."); if (input.quantity) remainingQuantity(batch.currentQuantity, "SALE", input.quantity); }
  const income = await db.transaction.create({ data: { userId, type: "INCOME", amount: decimal(totalAmount), operationDate: dateFromInput(input.operationDate), module: FinanceModule.POULTRY, categoryId: category.id, description: input.itemName, source: "WEB" } });
  const sale = await db.poultrySale.create({ data: { userId, batchId: input.batchId, buyer: input.buyer, itemName: input.itemName, quantity: input.quantity, weightKg: input.weightKg ? decimal(input.weightKg) : null, price: input.price ? decimal(input.price) : null, totalAmount: decimal(totalAmount), operationDate: dateFromInput(input.operationDate), comment: input.comment, incomeTransactionId: income.id } });
  if (batch && input.quantity) { await db.poultryMovement.create({ data: { userId, batchId: batch.id, type: "SALE", quantity: input.quantity, operationDate: dateFromInput(input.operationDate), comment: input.comment, saleId: sale.id } }); await db.poultryBatch.update({ where: { id: batch.id }, data: { currentQuantity: batch.currentQuantity - input.quantity } }); } return sale; }); }
export async function getPoultrySale(userId: string, id: string) { const sale = await prisma.poultrySale.findFirst({ where: { id, userId, deletedAt: null }, include: { batch: true } }); if (!sale) throw new Error("Продаж не знайдено."); return sale; }
export async function updatePoultrySale(userId: string, id: string, input: z.infer<typeof saleSchema>) {
  const totalAmount = saleTotal(input.quantity, input.weightKg, input.price, input.totalAmount);
  const category = await categoryByName(userId, "Продаж продукції", "INCOME");
  return prisma.$transaction(async (db) => {
    const current = await db.poultrySale.findFirst({ where: { id, userId, deletedAt: null }, include: { movement: true } });
    if (!current) throw new Error("Продаж не знайдено.");
    if (current.movement) await db.poultryBatch.update({ where: { id: current.movement.batchId }, data: { currentQuantity: { increment: current.movement.quantity } } });
    let nextBatch = null;
    if (input.batchId && input.quantity) {
      nextBatch = await db.poultryBatch.findFirst({ where: { id: input.batchId, userId, status: "ACTIVE", deletedAt: null } });
      if (!nextBatch) throw new Error("Активну партію не знайдено.");
      remainingQuantity(nextBatch.currentQuantity, "SALE", input.quantity);
      await db.poultryBatch.update({ where: { id: nextBatch.id }, data: { currentQuantity: nextBatch.currentQuantity - input.quantity } });
    }
    await db.transaction.update({ where: { id: current.incomeTransactionId }, data: { amount: decimal(totalAmount), operationDate: dateFromInput(input.operationDate), categoryId: category.id, description: input.itemName } });
    const sale = await db.poultrySale.update({ where: { id }, data: { batchId: input.batchId, buyer: input.buyer, itemName: input.itemName, quantity: input.quantity, weightKg: input.weightKg ? decimal(input.weightKg) : null, price: input.price ? decimal(input.price) : null, totalAmount: decimal(totalAmount), operationDate: dateFromInput(input.operationDate), comment: input.comment } });
    if (current.movement && nextBatch && input.quantity) await db.poultryMovement.update({ where: { id: current.movement.id }, data: { batchId: nextBatch.id, quantity: input.quantity, operationDate: dateFromInput(input.operationDate), comment: input.comment, deletedAt: null } });
    else if (current.movement) await db.poultryMovement.update({ where: { id: current.movement.id }, data: { deletedAt: new Date() } });
    else if (nextBatch && input.quantity) await db.poultryMovement.create({ data: { userId, batchId: nextBatch.id, type: "SALE", quantity: input.quantity, operationDate: dateFromInput(input.operationDate), comment: input.comment, saleId: sale.id } });
    return sale;
  });
}
export async function softDeletePoultrySale(userId: string, id: string) { return prisma.$transaction(async (db) => { const sale = await db.poultrySale.findFirst({ where: { id, userId, deletedAt: null }, include: { movement: true } }); if (!sale) throw new Error("Продаж не знайдено."); if (sale.movement) await db.poultryBatch.update({ where: { id: sale.movement.batchId }, data: { currentQuantity: { increment: sale.movement.quantity } } }); await db.poultryMovement.updateMany({ where: { saleId: sale.id, deletedAt: null }, data: { deletedAt: new Date() } }); await db.transaction.update({ where: { id: sale.incomeTransactionId }, data: { deletedAt: new Date() } }); return db.poultrySale.update({ where: { id }, data: { deletedAt: new Date() } }); }); }
export async function createFeedPurchase(userId: string, input: z.infer<typeof feedPurchaseSchema>) { const category = await categoryByName(userId, "Корма", "EXPENSE"); return prisma.$transaction(async (db) => { const product = await db.feedProduct.upsert({ where: { userId_name: { userId, name: input.name } }, update: { type: input.type, bagSizeKg: input.bagSizeKg ? decimal(input.bagSizeKg) : null }, create: { userId, name: input.name, type: input.type, bagSizeKg: input.bagSizeKg ? decimal(input.bagSizeKg) : null } }); const transaction = await db.transaction.create({ data: { userId, type: "EXPENSE", amount: decimal(input.totalAmount), operationDate: dateFromInput(input.operationDate), module: FinanceModule.POULTRY, categoryId: category.id, description: `Корм: ${input.name}`, source: "WEB" } }); return db.feedLot.create({ data: { userId, productId: product.id, purchaseTransactionId: transaction.id, purchasedBags: input.bags, availableBags: input.bags, costPerBag: decimal(input.totalAmount).div(input.bags), purchaseDate: dateFromInput(input.operationDate), comment: input.comment } }); }); }
export async function createFeedUsage(userId: string, input: z.infer<typeof feedUsageSchema> & { type?: "ASSIGNED" | "FINISHED" }) { return prisma.$transaction(async (db) => { const [lot, batch] = await Promise.all([db.feedLot.findFirst({ where: { id: input.lotId, userId, deletedAt: null } }), db.poultryBatch.findFirst({ where: { id: input.batchId, userId, deletedAt: null } })]); if (!lot || !batch) throw new Error("Корм або партію не знайдено."); const availableBags = remainingBags(lot.availableBags, input.bags); const usage = await db.feedUsage.create({ data: { lotId: lot.id, batchId: batch.id, bags: input.bags, type: input.type ?? "ASSIGNED", operationDate: dateFromInput(input.operationDate), comment: input.comment } }); await db.feedLot.update({ where: { id: lot.id }, data: { availableBags } }); return usage; }); }
export async function createIncubationBatch(userId: string, input: z.infer<typeof incubationSchema>) { return prisma.incubationBatch.create({ data: { userId, name: input.name, birdType: input.birdType, setDate: dateFromInput(input.setDate), comment: input.comment, items: { create: input.items } }, include: { items: true } }); }
export async function updateIncubationItem(userId: string, input: z.infer<typeof incubationUpdateSchema>) { const item = await prisma.incubationBatchItem.findFirst({ where: { id: input.itemId, incubationBatch: { userId, deletedAt: null } } }); if (!item || input.infertileQuantity + input.lossQuantity + input.hatchedQuantity > item.setQuantity) throw new Error("Показники інкубації перевищують закладену кількість."); return prisma.incubationBatchItem.update({ where: { id: input.itemId }, data: input }); }
export async function createBatchFromIncubation(userId: string, itemId: string) { const item = await prisma.incubationBatchItem.findFirst({ where: { id: itemId, poultryBatch: null, incubationBatch: { userId, deletedAt: null } }, include: { incubationBatch: true } }); if (!item || item.hatchedQuantity < 1) throw new Error("Немає доступної вилупленої птиці для створення партії."); return prisma.poultryBatch.create({ data: { userId, name: `${item.incubationBatch.name} · ${item.breed}`, birdType: item.incubationBatch.birdType, breed: item.breed, startDate: item.incubationBatch.setDate, startingQuantity: item.hatchedQuantity, currentQuantity: item.hatchedQuantity, source: "INCUBATION", comment: `Створено з інкубації ${item.incubationBatch.name}`, incubationBatchId: item.incubationBatchId, incubationItemId: item.id } }); }
export async function createOperationalExpense(userId: string, input: z.infer<typeof operationalExpenseSchema>) { await poultryCategory(userId, input.categoryId, "EXPENSE"); if (input.batchId && !await prisma.poultryBatch.findFirst({ where: { id: input.batchId, userId, deletedAt: null } })) throw new Error("Партію не знайдено."); return prisma.$transaction(async (db) => { const transaction = await db.transaction.create({ data: { userId, type: "EXPENSE", amount: decimal(input.amount), operationDate: dateFromInput(input.operationDate), module: FinanceModule.POULTRY, categoryId: input.categoryId, description: input.description, source: "WEB" } }); return db.poultryOperationalExpense.create({ data: { userId, transactionId: transaction.id, batchId: input.batchId } }); }); }
export async function getPoultryDashboard(userId: string, period: "TODAY" | "WEEK" | "MONTH" | "YEAR" = "MONTH") { const from = periodStart(period, dateFromInput(todayInputValue())); const [batches, lots, incubations, sales, transactions] = await Promise.all([prisma.poultryBatch.findMany({ where: { userId, deletedAt: null }, include: { feedUsages: { include: { lot: { include: { product: true } } } }, sales: { where: { deletedAt: null } } }, orderBy: { startDate: "desc" } }), prisma.feedLot.findMany({ where: { userId, deletedAt: null }, include: { product: true }, orderBy: { purchaseDate: "desc" } }), prisma.incubationBatch.findMany({ where: { userId, deletedAt: null }, include: { items: { include: { poultryBatch: true } } }, orderBy: { setDate: "desc" } }), prisma.poultrySale.findMany({ where: { userId, deletedAt: null }, include: { batch: true }, orderBy: { operationDate: "desc" } }), prisma.transaction.findMany({ where: { userId, module: FinanceModule.POULTRY, deletedAt: null, operationDate: { gte: from } }, include: { category: true } })]); return { report: poultryReport(transactions.map((item) => ({ type: item.type as "INCOME" | "EXPENSE", amount: item.amount.toString(), categoryName: item.category?.name }))), batches: batches.map((batch) => ({ ...batch, ageDays: poultryAgeDays(batch.startDate, dateFromInput(todayInputValue())), feedCost: batch.feedUsages.reduce((sum, usage) => sum.plus(usage.lot.costPerBag.mul(usage.bags)), new Prisma.Decimal(0)) })), lots, incubations: incubations.map((batch) => ({ ...batch, items: batch.items.map((item) => ({ ...item, hatchRate: hatchRate(item.setQuantity, item.hatchedQuantity) })) })), sales }; }
export function formValue(formData: FormData, name: string) { return optional(formData.get(name)); }
