"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";

import { requireUser } from "@/server/auth";
import { createGoodsOperationalExpense, createInventoryChange, createProduct, createProductCategory, createProductPurchase, createProductSale, deleteProductPurchase, deleteProductSale, formValue, goodsExpenseSchema, inventoryChangeSchema, productCategorySchema, productSchema, purchaseSchema, saleSchema, updateProductPurchase, updateProductSale } from "@/server/goods";

const refresh = () => ["/goods", "/goods/inventory", "/goods/purchases", "/goods/sales", "/goods/expenses", "/dashboard", "/projects", "/reports", "/finance"].forEach((path) => revalidatePath(path));
const done = (key: string) => { refresh(); redirect(`/goods?${key}=1`); };

export async function createProductAction(formData: FormData) { const user = await requireUser(); await createProduct(user.id, productSchema.parse({ name: formData.get("name"), categoryId: formValue(formData, "categoryId"), brand: formValue(formData, "brand"), unit: formData.get("unit"), openingQuantity: formData.get("openingQuantity") || "0", openingUnitCost: formValue(formData, "openingUnitCost"), openingDate: formData.get("openingDate"), defaultSalePrice: formValue(formData, "defaultSalePrice"), comment: formValue(formData, "comment") })); done("product"); }
export async function createProductCategoryAction(formData: FormData) { const user = await requireUser(); await createProductCategory(user.id, productCategorySchema.parse({ name: formData.get("name") })); done("category"); }
export async function createPurchaseAction(formData: FormData) { const user = await requireUser(); await createProductPurchase(user.id, purchaseSchema.parse({ productId: formData.get("productId"), quantity: formData.get("quantity"), unitPurchasePrice: formData.get("unitPurchasePrice"), deliveryAmount: formValue(formData, "deliveryAmount"), deliveryInCost: formData.get("deliveryInCost") === "on", supplier: formValue(formData, "supplier"), operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") })); done("purchase"); }
export async function createSaleAction(formData: FormData) { const user = await requireUser(); await createProductSale(user.id, saleSchema.parse({ productId: formData.get("productId"), quantity: formData.get("quantity"), unitSalePrice: formData.get("unitSalePrice"), totalAmount: formValue(formData, "totalAmount"), buyer: formValue(formData, "buyer"), operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") })); done("sale"); }
export async function updateSaleAction(formData: FormData) { const user = await requireUser(); const id = formData.get("id"); if (typeof id !== "string") throw new Error("Продажа не найдена."); await updateProductSale(user.id, id, saleSchema.parse({ productId: formData.get("productId"), quantity: formData.get("quantity"), unitSalePrice: formData.get("unitSalePrice"), totalAmount: formValue(formData, "totalAmount"), buyer: formValue(formData, "buyer"), operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") })); done("saleUpdated"); }
export async function deleteSaleAction(formData: FormData) { const user = await requireUser(); const id = formData.get("id"); if (typeof id !== "string") throw new Error("Продажа не найдена."); await deleteProductSale(user.id, id); done("saleDeleted"); }
export async function updatePurchaseAction(formData: FormData) { const user = await requireUser(); const id = formData.get("id"); if (typeof id !== "string") throw new Error("Закупка не найдена."); await updateProductPurchase(user.id, id, purchaseSchema.parse({ productId: formData.get("productId"), quantity: formData.get("quantity"), unitPurchasePrice: formData.get("unitPurchasePrice"), deliveryAmount: formValue(formData, "deliveryAmount"), deliveryInCost: formData.get("deliveryInCost") === "on", supplier: formValue(formData, "supplier"), operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") })); done("purchaseUpdated"); }
export async function deletePurchaseAction(formData: FormData) { const user = await requireUser(); const id = formData.get("id"); if (typeof id !== "string") throw new Error("Закупка не найдена."); await deleteProductPurchase(user.id, id); done("purchaseDeleted"); }
export async function createInventoryChangeAction(formData: FormData) { const user = await requireUser(); await createInventoryChange(user.id, inventoryChangeSchema.parse({ productId: formData.get("productId"), quantity: formData.get("quantity"), operationDate: formData.get("operationDate"), comment: formData.get("comment"), type: formData.get("type") })); done("inventory"); }
export async function createGoodsExpenseAction(formData: FormData) { const user = await requireUser(); await createGoodsOperationalExpense(user.id, goodsExpenseSchema.parse({ categoryId: formData.get("categoryId"), amount: formData.get("amount"), operationDate: formData.get("operationDate"), description: formData.get("description") })); done("expense"); }
