import Link from "next/link";
import { AppIcon } from "@/components/ui/icons";
import { SectionHeader } from "@/components/ui/section-header";
import { formatMoney } from "@/lib/money";
import { requireUser } from "@/server/auth";
import { getGoodsDashboard } from "@/server/goods";

const periods = { TODAY: "Сегодня", WEEK: "Неделя", MONTH: "Месяц", YEAR: "Год" } as const;
const sections = [["/goods/inventory", "flock", "Товары и склад", "Остатки и стоимость"], ["/goods/purchases", "feed", "Закупки", "Партии и расходы"], ["/goods/sales", "sales", "Продажи", "Выручка и прибыль"], ["/goods/expenses", "expense", "Операционные расходы", "Реклама, доставка и прочее"], ["/reports?project=goods", "money", "Финансы", "Деньги и торговая прибыль"]] as const;
export default async function GoodsPage({ searchParams }: { searchParams: Promise<{ period?: string }> }) { const user = await requireUser(); const { period: raw } = await searchParams; const period = raw && raw in periods ? raw as keyof typeof periods : "MONTH"; const { products, report } = await getGoodsDashboard(user.id, period); return <><header className="page-header"><div><p className="eyebrow">Проект</p><h1>Товарка</h1><p className="muted">Закупки, остатки и продажи без двойного учёта.</p></div><Link href="/goods/inventory" className="button primary">＋</Link></header><form className="period-tabs" action="/goods">{Object.entries(periods).map(([value, label]) => <button key={value} name="period" value={value} className={period === value ? "active" : ""}>{label}</button>)}</form><section className="metric-grid poultry-summary"><article><span>Доход</span><strong className="income">{formatMoney(report.income)}</strong></article><article><span>Расход</span><strong className="expense">{formatMoney(report.expense)}</strong></article><article><span>Денежный результат</span><strong>{formatMoney(report.cashResult)}</strong></article><article><span>Прибыль продаж</span><strong className="income">{formatMoney(report.profit)}</strong></article></section><SectionHeader eyebrow="Разделы" title="Что хотите сделать?"/><section className="poultry-section-grid">{sections.map(([href, icon, title, description]) => <Link href={href} key={href} className="poultry-section-card"><AppIcon name={icon}/><b>{title}</b><span>{description}</span></Link>)}</section><SectionHeader eyebrow="Склад" title="Товары сейчас" action={<Link href="/goods/inventory" className="text-link">Открыть склад</Link>}/><div className="transaction-list">{products.slice(0, 5).map((product) => <Link href="/goods/inventory" className="transaction-row" key={product.id}><span><b>{product.name}</b><small>{product.category?.name ?? "Без категории"}</small></span><strong>{product.currentQuantity} шт.</strong></Link>)}{products.length === 0 && <p className="empty">Товаров пока нет. Добавьте первый товар.</p>}</div></>; }
