import { requireUser } from "@/server/auth";
import { getPoultryCategories } from "@/server/poultry";
import { archivePoultryCategoryAction, createPoultryCategoryAction, deletePoultryCategoryAction, movePoultryCategoryAction, updatePoultryCategoryAction } from "../../actions";

const errors: Record<string, string> = { duplicate: "Такая категория уже существует.", used: "Категория используется в истории — её можно только архивировать.", protected: "Системная категория защищена. Создайте свою категорию для изменений." };

export default async function PoultryCategoriesPage({ searchParams }: { searchParams: Promise<{ error?: string }> }) {
  const user = await requireUser();
  const [categories, query] = await Promise.all([getPoultryCategories(user.id, true), searchParams]);
  return <>
    <header className="page-header compact-page-header"><div><p className="eyebrow">Настройки</p><h1>Категории расходов</h1><p className="muted">Использованные категории сохраняются в истории</p></div></header>
    {query.error && errors[query.error] && <p className="form-error">{errors[query.error]}</p>}
    <div className="settings-list">{categories.map((category) => <article className={`settings-editor ${category.isArchived ? "archived" : ""}`} key={category.id}><div className="settings-row-title"><span className="settings-icon">{category.icon || "•"}</span><span><b>{category.name}</b><small>{category.userId ? `${category._count.transactions} операций${category.isArchived ? " · в архиве" : ""}` : "Системная категория"}</small></span></div>{category.userId && <details className="inline-editor"><summary>Изменить</summary><form action={updatePoultryCategoryAction} className="compact-form"><input type="hidden" name="id" value={category.id}/><input type="hidden" name="returnTo" value="/poultry/settings/categories"/><div className="form-grid"><label>Название<input name="name" required defaultValue={category.name}/></label><label>Иконка<input name="icon" defaultValue={category.icon ?? ""} placeholder="💊"/></label></div><button className="button primary">Сохранить</button></form><div className="inline-settings-actions"><form action={movePoultryCategoryAction}><input type="hidden" name="id" value={category.id}/><button name="direction" value="UP" className="text-button">↑</button><button name="direction" value="DOWN" className="text-button">↓</button></form><form action={archivePoultryCategoryAction}><input type="hidden" name="id" value={category.id}/><input type="hidden" name="archived" value={category.isArchived ? "0" : "1"}/><button className="text-button">{category.isArchived ? "Восстановить" : "Архивировать"}</button></form>{category._count.transactions === 0 && <form action={deletePoultryCategoryAction}><input type="hidden" name="id" value={category.id}/><button className="text-button danger-text">Удалить</button></form>}</div></details>}</article>)}</div>
    <details className="app-card action-drawer"><summary><b>＋ Добавить категорию</b><span>＋</span></summary><form action={createPoultryCategoryAction} className="compact-form"><input type="hidden" name="returnTo" value="/poultry/settings/categories"/><div className="form-grid"><label>Название<input name="name" required placeholder="Ветеринария"/></label><label>Иконка<input name="icon" placeholder="💊"/></label></div><button className="button primary">Добавить</button></form></details>
  </>;
}
