import Link from "next/link";

import { CompleteCosmetologyVisitForm } from "@/components/complete-cosmetology-visit-form";
import { CosmetologyVisitServices } from "@/components/cosmetology-visit-services";
import { ConfirmationDialog } from "@/components/ui/confirmation-dialog";
import { todayInputValue } from "@/lib/dates";
import { formatMoney } from "@/lib/money";
import { requireUser } from "@/server/auth";
import { getCosmetologyDashboard, getCosmetologyVisit } from "@/server/cosmetology";

import { addCosmetologyVisitServiceAction, completeCosmetologyVisitAction, deleteCosmetologyVisitAction, removeCosmetologyVisitServiceAction, updateCosmetologyVisitServiceAction } from "../../actions";

export default async function VisitPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requireUser();
  const { id } = await params;
  const [visit, dashboard] = await Promise.all([getCosmetologyVisit(user.id, id), getCosmetologyDashboard(user.id)]);
  const clientName = visit.client.displayName ?? `${visit.client.lastName} ${visit.client.firstName}`;

  if (visit.status === "SCHEDULED") return <><header className="page-header"><div><p className="eyebrow">Косметология · Запись</p><h1>{visit.procedureName}</h1><p className="muted">{clientName} · {visit.operationDate.toLocaleDateString("ru-RU")}{visit.scheduledTime ? ` · ${visit.scheduledTime}` : ""}{visit.durationMinutes ? ` · ${visit.durationMinutes} мин` : ""}</p></div><Link href="/cosmetology/visits" className="text-link">К записям</Link></header><section className="family-grid"><article className="app-card"><CosmetologyVisitServices visitId={visit.id} services={visit.services.map((service) => ({ id: service.id, templateId: service.templateId, name: service.name, price: service.price.toString(), durationMinutes: service.durationMinutes, materials: service.template?.materials.map((material) => `${material.item.name} · ${material.quantity.toString()}`) ?? [] }))} templates={dashboard.templates.map((template) => ({ id: template.id, name: template.name, basePrice: template.basePrice?.toString() ?? null, durationMinutes: template.durationMinutes, materials: template.materials.map((material) => `${material.item.name} · ${material.quantity.toString()}`) }))} addAction={addCosmetologyVisitServiceAction} updateAction={updateCosmetologyVisitServiceAction} removeAction={removeCosmetologyVisitServiceAction}/></article><article className="app-card"><h2>Закрыть процедуру</h2><p className="summary-note">Предоплата: {formatMoney(visit.paidAmount.toString())}. При закрытии спишутся материалы из техкарт всех услуг.</p><CompleteCosmetologyVisitForm visit={{ id: visit.id, plannedAmount: visit.plannedAmount?.toString() ?? null, comment: visit.comment }} items={dashboard.items.filter((item) => item.currentQuantity.gt(0)).map((item) => ({ id: item.id, name: item.name, quantity: item.currentQuantity.toString() }))} today={todayInputValue()} action={completeCosmetologyVisitAction}/></article></section><div className="danger-zone"><h2>Отмена записи</h2><p>Запись будет удалена без операций в финансах и на складе.</p><ConfirmationDialog action={deleteCosmetologyVisitAction} fieldName="id" fieldValue={visit.id} trigger="Отменить запись" title="Отменить запись?" description="Доход и материалы ещё не создавались." confirmLabel="Отменить" triggerClassName="text-link"/></div></>;

  return <><header className="page-header"><div><p className="eyebrow">Косметология · Завершено</p><h1>{visit.procedureName}</h1><p className="muted">{clientName} · {visit.operationDate.toLocaleDateString("ru-RU")}</p></div><Link href="/cosmetology/visits" className="text-link">К записям</Link></header><section className="metric-grid"><article><span>Доход</span><strong className="income">{formatMoney(visit.paymentAmount.toString())}</strong></article><article><span>Себестоимость</span><strong>{formatMoney(visit.costAmount.toString())}</strong></article><article><span>Прибыль</span><strong>{formatMoney(visit.profitAmount.toString())}</strong></article></section><section className="app-card"><h2>Фактически списано</h2><div className="mini-list">{visit.usages.map((usage) => <div key={usage.id}><span>{usage.item.name} · {usage.quantity.toString()}</span><b>{formatMoney(usage.totalCost.toString())}</b></div>)}{!visit.usages.length && <p className="muted">Материалы не списывались.</p>}</div></section><div className="danger-zone"><h2>Удаление</h2><p>Доход будет исключён из отчётов, а материалы вернутся на склад.</p><ConfirmationDialog action={deleteCosmetologyVisitAction} fieldName="id" fieldValue={visit.id} trigger="Удалить процедуру" title="Удалить завершённую процедуру?" description="Доход будет исключён из расчётов, а материалы вернутся на склад." confirmLabel="Удалить" triggerClassName="text-link"/></div></>;
}
