import Link from "next/link";

import { formatMoney } from "@/lib/money";
import { dateToInput } from "@/lib/dates";
import { requireUser } from "@/server/auth";
import { getInfoProduct, infoProductTypes } from "@/server/infobusiness";
import { updateInfoProductAction } from "../../actions";

export default async function InfoProductPage({ params }: { params: Promise<{ id: string }> }) {
  const user = await requireUser(); const { id } = await params; const product = await getInfoProduct(user.id, id);
  return <><header className="page-header"><div><p className="eyebrow">Инфобизнес · Курс</p><h1>{product.name}</h1><p className="muted">Доходы и только прямо привязанные к этому продукту расходы.</p></div><Link className="button secondary" href="/infobusiness/products">К курсам</Link></header>
    <section className="metric-grid family-summary"><article><span>Продажи</span><strong>{product.summary.sales}</strong></article><article><span>Доход</span><strong className="income">{formatMoney(product.summary.income)}</strong></article><article><span>Расходы курса</span><strong className="expense">{formatMoney(product.summary.expense)}</strong></article><article><span>Прибыль</span><strong>{formatMoney(product.summary.profit)}</strong></article></section>
    <section className="family-grid"><article className="app-card"><h2>Карточка продукта</h2><form action={updateInfoProductAction} className="compact-form"><input type="hidden" name="id" value={product.id}/><label>Название<input name="name" required defaultValue={product.name}/></label><div className="form-grid"><label>Тип<input name="type" required list="info-product-types" defaultValue={product.type}/></label><label>Формат<select name="format" defaultValue={product.format}><option value="ONLINE">Онлайн</option><option value="OFFLINE">Офлайн</option><option value="HYBRID">Гибридный</option></select></label></div><div className="form-grid"><label>Базовая цена<input name="basePrice" inputMode="decimal" defaultValue={product.basePrice?.toString() ?? ""}/></label><label>Статус<select name="status" defaultValue={product.status}><option value="PREPARATION">Подготовка</option><option value="ACTIVE">Активный</option><option value="COMPLETED">Завершён</option><option value="ARCHIVED">Архив</option></select></label></div><div className="form-grid"><label>Дата начала<input name="startDate" type="date" defaultValue={product.startDate ? dateToInput(product.startDate) : ""}/></label><label>Дата окончания<input name="endDate" type="date" defaultValue={product.endDate ? dateToInput(product.endDate) : ""}/></label></div><label>Комментарий<input name="comment" defaultValue={product.comment ?? ""}/></label><button className="button primary">Сохранить</button></form><datalist id="info-product-types">{infoProductTypes.map((type) => <option key={type} value={type}/>)}</datalist></article><article className="app-card"><h2>Принцип расчёта</h2><p className="muted">Общие расходы Инфобизнеса не вычитаются из прибыли этого курса и не распределяются автоматически.</p></article></section>
    <section className="section-header"><div><p className="eyebrow">История</p><h2>Последние продажи</h2></div><Link className="text-link" href="/infobusiness/sales">Все продажи</Link></section><div className="transaction-list">{product.sales.slice(0, 8).map((sale) => <Link href={`/infobusiness/sales/${sale.id}`} className="transaction-row" key={sale.id}><span><b>{sale.buyer || "Продажа обучения"}</b><small>{sale.incomeTransaction.operationDate.toLocaleDateString("ru-RU")}{sale.seats !== 1 ? ` · ${sale.seats} мест` : ""}</small></span><strong className="income">+{formatMoney(sale.incomeTransaction.amount.toString())}</strong></Link>)}</div>{product.sales.length === 0 && <p className="empty">Продаж курса пока нет.</p>}
    <section className="section-header"><div><p className="eyebrow">Затраты</p><h2>Расходы курса</h2></div><Link className="text-link" href="/infobusiness/expenses">Добавить</Link></section><div className="transaction-list">{product.expenses.slice(0, 8).map((expense) => <Link href={`/infobusiness/expenses/${expense.id}`} className="transaction-row" key={expense.id}><span><b>{expense.transaction.description ?? expense.category.name}</b><small>{expense.category.name} · {expense.transaction.operationDate.toLocaleDateString("ru-RU")}</small></span><strong className="expense">−{formatMoney(expense.transaction.amount.toString())}</strong></Link>)}</div>{product.expenses.length === 0 && <p className="empty">Привязанных расходов пока нет.</p>}</>;
}
