import Link from "next/link";

import { PoultryFormActions } from "@/components/poultry-form-actions";
import { EmptyState } from "@/components/ui/empty-state";
import { SectionHeader } from "@/components/ui/section-header";
import { StatusBadge } from "@/components/ui/app-card";
import { todayInputValue } from "@/lib/dates";
import { requireUser } from "@/server/auth";
import { getPoultryDashboard } from "@/server/poultry";
import { createPoultryBatchAction, createPoultryMovementAction, createPoultryTransferAction, createSlaughterAction, reconcileFlockAction } from "../actions";

export default async function FlockPage({ searchParams }: { searchParams: Promise<{ batchId?: string; returnTo?: string }> }) {
  const user = await requireUser();
  const { batches } = await getPoultryDashboard(user.id);
  const active = batches.filter((batch) => batch.status === "ACTIVE");
  const currentQuantity = active.reduce((total, batch) => total + batch.currentQuantity, 0);
  const today = todayInputValue();
  const query = await searchParams;
  const selectedBatchId = active.some((batch) => batch.id === query.batchId) ? query.batchId ?? "" : "";
  const returnTo = query.returnTo?.startsWith("/poultry") && !query.returnTo.startsWith("//") ? query.returnTo : "/poultry/flock";

  return <>
    <header className="page-header"><div><p className="eyebrow">Птицеводство</p><h1>Птица</h1><p className="muted">Группы содержания, происхождение и все изменения поголовья.</p></div><Link href="/poultry" className="button secondary">Обзор</Link></header>
    <section className="balance-card"><p>Поголовье сейчас</p><strong>{currentQuantity} гол.</strong><span>{active.length} активн. групп</span></section>

    <SectionHeader eyebrow="Группы" title="Что есть сейчас" />
    {batches.length ? <section className="project-grid">{batches.map((batch) => <Link className="project-card active" href={`/poultry/flock/${batch.id}`} key={batch.id}><div className="card-title"><h3>{batch.name}</h3><StatusBadge tone={batch.status === "ACTIVE" ? "success" : "neutral"}>{batch.status === "ACTIVE" ? "Активна" : "Завершена"}</StatusBadge></div><span>{batch.birdType}{batch.breeds.length ? ` · ${batch.breeds.map((item) => item.name).join(", ")}` : ""}</span><strong>{batch.currentQuantity} гол.</strong><small>Возраст: {batch.ageDays} дн. · ≈ {batch.currentQuantity ? (batch.productionCost.total / batch.currentQuantity).toFixed(2) : "0.00"} ₴/гол.</small><em>Открыть паспорт →</em></Link>)}</section> : <EmptyState title="Пока нет групп птицы" description="Добавьте купленную, подаренную или другую птицу." />}

    <SectionHeader eyebrow="Быстро" title="Изменить поголовье" />
    <section className="poultry-action-panels">
      <details id="movement" className="app-card"><summary><b>Падёж или другое изменение</b><span>＋</span></summary><form action={createPoultryMovementAction} className="compact-form"><input type="hidden" name="returnTo" value={returnTo}/><label>Группа<select name="batchId" required defaultValue={selectedBatchId}><option value="" disabled>Выберите группу</option>{active.map((batch) => <option value={batch.id} key={batch.id}>{batch.name} · {batch.currentQuantity}</option>)}</select></label><div className="form-grid"><label>Событие<select name="type"><option value="MORTALITY">Падёж</option><option value="FAMILY_USE">Другое выбытие</option><option value="ADD">Дополнительное поступление</option></select></label><label>Количество<input name="quantity" required inputMode="numeric" /></label></div><label>Причина<input name="reason" placeholder="Необязательно" /></label><label>Дата<input name="operationDate" type="date" required defaultValue={today} /></label><label>Комментарий<input name="comment" /></label><PoultryFormActions cancelHref={returnTo}><button className="button secondary">Сохранить событие</button></PoultryFormActions></form></details>

      <details id="transfer" className="app-card"><summary><b>Перевести между группами</b><span>＋</span></summary><form action={createPoultryTransferAction} className="compact-form"><input type="hidden" name="returnTo" value={returnTo}/><label>Откуда<select name="sourceBatchId" required defaultValue={selectedBatchId}><option value="" disabled>Исходная группа</option>{active.map((batch) => <option value={batch.id} key={batch.id}>{batch.name} · {batch.currentQuantity}</option>)}</select></label><label>Куда<select name="destinationBatchId" defaultValue=""><option value="">Создать новую группу</option>{active.map((batch) => <option value={batch.id} key={batch.id}>{batch.name}</option>)}</select></label><label>Название новой группы<input name="destinationName" placeholder="Например, Петухи на откорм" /></label><div className="form-grid"><label>Количество<input name="quantity" required inputMode="numeric" /></label><label>Дата<input name="operationDate" type="date" required defaultValue={today} /></label></div><label>Комментарий<input name="comment" /></label><p className="summary-note">Общее поголовье и деньги не меняются. Производственная стоимость переносится пропорционально.</p><PoultryFormActions cancelHref={returnTo}><button className="button secondary">Перевести</button></PoultryFormActions></form></details>

      <details id="slaughter" className="app-card"><summary><b>Забой</b><span>＋</span></summary><form action={createSlaughterAction} className="compact-form"><input type="hidden" name="returnTo" value={returnTo}/><label>Группа<select name="batchId" required defaultValue={selectedBatchId}><option value="" disabled>Выберите группу</option>{active.map((batch) => <option value={batch.id} key={batch.id}>{batch.name} · {batch.currentQuantity}</option>)}</select></label><div className="form-grid"><label>Количество<input name="quantity" required inputMode="numeric" /></label><label>Назначение<select name="purpose"><option value="FAMILY">Для семьи</option><option value="SALE">На продажу</option></select></label></div><div className="form-grid"><label>Вес тушек, кг<input name="carcassWeightKg" inputMode="decimal" placeholder="Необязательно" /></label><label>Дата<input name="operationDate" type="date" required defaultValue={today} /></label></div><label>Комментарий<input name="comment" /></label><PoultryFormActions cancelHref={returnTo}><button className="button secondary">Записать забой</button></PoultryFormActions></form></details>

      <details id="reconcile" className="app-card"><summary><b>Сверить поголовье</b><span>＋</span></summary><form action={reconcileFlockAction} className="compact-form"><input type="hidden" name="returnTo" value={returnTo}/><label>Группа<select name="batchId" required defaultValue={selectedBatchId}><option value="" disabled>Выберите группу</option>{active.map((batch) => <option value={batch.id} key={batch.id}>{batch.name} · FEVORA {batch.currentQuantity}</option>)}</select></label><div className="form-grid"><label>Фактически голов<input name="actualQuantity" required inputMode="numeric" /></label><label>Дата<input name="operationDate" type="date" required defaultValue={today} /></label></div><label>Комментарий<input name="comment" /></label><PoultryFormActions cancelHref={returnTo}><button className="button secondary">Создать корректировку</button></PoultryFormActions></form></details>
    </section>

    <SectionHeader eyebrow="Поступление" title="Добавить или купить птицу" />
    <article id="new-batch" className="app-card"><form action={createPoultryBatchAction} className="compact-form"><input type="hidden" name="returnTo" value={returnTo}/><label>Название группы<input name="name" required placeholder="Утки · август" /></label><div className="form-grid"><label>Вид птицы<input name="birdType" required placeholder="Утки" /></label><label>Способ поступления<select name="source"><option value="PURCHASE">Покупка</option><option value="GIFT">Подарок / бесплатно</option><option value="OTHER">Другое</option></select></label></div><div className="form-grid"><label>Дата появления / покупки<input name="startDate" type="date" required defaultValue={today} /></label><label>Количество<input name="quantity" required inputMode="numeric" /></label></div><details className="form-details"><summary>Возраст и породы — необязательно</summary><label>Возраст при покупке, дней<input name="ageAtAcquisitionDays" inputMode="numeric" /></label>{[0,1,2,3].map((index) => <div className="form-grid" key={index}><label>Порода<input name={`breed-${index}`} placeholder={index ? "Ещё порода" : "Неизвестно"} /></label><label>Голов<input name={`breedQuantity-${index}`} inputMode="numeric" /></label></div>)}</details><div className="form-grid"><label>Оплачено, ₴<input name="cashCost" inputMode="decimal" placeholder="Для покупки" /></label><label>Расчётная стоимость, ₴<input name="productionValue" inputMode="decimal" placeholder="Для подаренной птицы" /></label></div><p className="summary-note">Оплата создаст один реальный расход. Расчётная стоимость подарка увеличит только себестоимость.</p><label>Комментарий<input name="comment" /></label><PoultryFormActions cancelHref={returnTo}><button className="button primary">Создать группу</button></PoultryFormActions></form></article>
  </>;
}
