"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";

import { requireUser } from "@/server/auth";
import { batchSchema, createBatchFromIncubation, createEggCollection, createFeedAdjustment, createFeedPurchase, createFeedRate, createFeedUsage, createIncubationBatch, createOperationalExpense, createPoultryBatch, createPoultryMovement, createPoultrySale, createPoultryTransfer, createSlaughter, eggCollectionSchema, feedAdjustmentSchema, feedPurchaseSchema, feedRateSchema, feedUsageSchema, formValue, incubationSchema, incubationUpdateSchema, movementSchema, operationalExpenseSchema, reconcileFlock, reconciliationSchema, saleSchema, slaughterSchema, softDeleteEggCollection, softDeleteOperationalExpense, softDeletePoultrySale, transferSchema, updateIncubationItem, updatePoultrySale } from "@/server/poultry";

const refresh = () => ["/dashboard", "/poultry", "/poultry/flock", "/poultry/feed", "/poultry/eggs", "/poultry/analytics", "/projects", "/reports", "/finance"].forEach((path) => revalidatePath(path));
const required = (formData: FormData, name: string) => { const value = formData.get(name); if (typeof value !== "string") throw new Error("Перевірте форму."); return value; };
const done = (formData: FormData, fallbackPath: string, key: string) => {
  refresh();
  const requested = formValue(formData, "returnTo");
  const safePath = requested?.startsWith("/poultry") && !requested.startsWith("//") ? requested : fallbackPath;
  const target = new URL(safePath, "http://fevora.local");
  target.searchParams.set(key, "1");
  redirect(`${target.pathname}${target.search}${target.hash}`);
};

export async function createPoultryBatchAction(formData: FormData) {
  const user = await requireUser();
  const breeds = [0, 1, 2, 3].map((index) => ({ name: formValue(formData, `breed-${index}`), quantity: formValue(formData, `breedQuantity-${index}`) })).filter((item) => item.quantity).map((item) => ({ name: item.name, quantity: Number(item.quantity) }));
  await createPoultryBatch(user.id, batchSchema.parse({ name: formData.get("name"), birdType: formData.get("birdType"), breed: formValue(formData, "breed"), breeds: breeds.length ? breeds : undefined, startDate: formData.get("startDate"), acquisitionDate: formData.get("acquisitionDate") || formData.get("startDate"), ageAtAcquisitionDays: formValue(formData, "ageAtAcquisitionDays") ? Number(formValue(formData, "ageAtAcquisitionDays")) : null, quantity: formData.get("quantity"), source: formData.get("source"), cashCost: formValue(formData, "cashCost"), productionValue: formValue(formData, "productionValue"), comment: formValue(formData, "comment") }));
  done(formData, "/poultry/flock", "batch");
}

export async function createPoultryMovementAction(formData: FormData) { const user = await requireUser(); await createPoultryMovement(user.id, movementSchema.parse({ batchId: formData.get("batchId"), type: formData.get("type"), quantity: formData.get("quantity"), operationDate: formData.get("operationDate"), reason: formValue(formData, "reason"), comment: formValue(formData, "comment") })); done(formData, "/poultry/flock", "movement"); }
export async function reconcileFlockAction(formData: FormData) { const user = await requireUser(); await reconcileFlock(user.id, reconciliationSchema.parse({ batchId: formData.get("batchId"), actualQuantity: formData.get("actualQuantity"), operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") })); done(formData, "/poultry/flock", "reconciled"); }
export async function createPoultryTransferAction(formData: FormData) { const user = await requireUser(); await createPoultryTransfer(user.id, transferSchema.parse({ sourceBatchId: formData.get("sourceBatchId"), destinationBatchId: formValue(formData, "destinationBatchId"), destinationName: formValue(formData, "destinationName"), quantity: formData.get("quantity"), operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") })); done(formData, "/poultry/flock", "transfer"); }
export async function createSlaughterAction(formData: FormData) { const user = await requireUser(); await createSlaughter(user.id, slaughterSchema.parse({ batchId: formData.get("batchId"), quantity: formData.get("quantity"), purpose: formData.get("purpose"), carcassWeightKg: formValue(formData, "carcassWeightKg"), operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") })); done(formData, "/poultry/flock", "slaughter"); }

const saleInput = (formData: FormData) => saleSchema.parse({ saleType: formData.get("saleType") || "LIVE_BIRD", batchId: formValue(formData, "batchId"), slaughterId: formValue(formData, "slaughterId"), buyer: formValue(formData, "buyer"), buyerPhone: formValue(formData, "buyerPhone"), itemName: formData.get("itemName"), quantity: formValue(formData, "quantity") ? Number(formValue(formData, "quantity")) : null, weightKg: formValue(formData, "weightKg"), price: formValue(formData, "price"), totalAmount: formValue(formData, "totalAmount"), operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") });
export async function createPoultrySaleAction(formData: FormData) { const user = await requireUser(); await createPoultrySale(user.id, saleInput(formData)); done(formData, "/poultry/sales", "sale"); }
export async function updatePoultrySaleAction(formData: FormData) { const user = await requireUser(); await updatePoultrySale(user.id, required(formData, "id"), saleInput(formData)); done(formData, "/poultry/sales", "updated"); }
export async function deletePoultrySaleAction(formData: FormData) { const user = await requireUser(); await softDeletePoultrySale(user.id, required(formData, "id")); done(formData, "/poultry/sales", "deleted"); }

export async function createFeedPurchaseAction(formData: FormData) { const user = await requireUser(); await createFeedPurchase(user.id, feedPurchaseSchema.parse({ name: formData.get("name"), type: formValue(formData, "type"), unit: formData.get("unit") || "BAG", quantity: formValue(formData, "quantity"), bags: formValue(formData, "bags") ? Number(formValue(formData, "bags")) : undefined, bagSizeKg: formValue(formData, "bagSizeKg"), householdUnitName: formValue(formData, "householdUnitName"), householdUnitKg: formValue(formData, "householdUnitKg"), totalAmount: formData.get("totalAmount"), operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") })); done(formData, "/poultry/feed", "purchase"); }
export async function createFeedUsageAction(formData: FormData) { const user = await requireUser(); await createFeedUsage(user.id, { ...feedUsageSchema.parse({ lotId: formData.get("lotId"), batchId: formData.get("batchId"), unit: formData.get("unit") || "BAG", quantity: formValue(formData, "quantity"), bags: formValue(formData, "bags") ? Number(formValue(formData, "bags")) : undefined, operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") }), type: formData.get("type") === "FINISHED" ? "FINISHED" : "ASSIGNED" }); done(formData, "/poultry/feed", "usage"); }
export async function createFeedRateAction(formData: FormData) { const user = await requireUser(); await createFeedRate(user.id, feedRateSchema.parse({ batchId: formData.get("batchId"), productId: formData.get("productId"), unit: formData.get("unit"), dailyQuantity: formData.get("dailyQuantity"), effectiveFrom: formData.get("effectiveFrom"), comment: formValue(formData, "comment") })); done(formData, "/poultry/feed", "rate"); }
export async function createFeedAdjustmentAction(formData: FormData) { const user = await requireUser(); await createFeedAdjustment(user.id, feedAdjustmentSchema.parse({ productId: formData.get("productId"), actualKg: formData.get("actualKg"), operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") })); done(formData, "/poultry/feed", "adjustment"); }

export async function createIncubationAction(formData: FormData) { const user = await requireUser(); const items = [0, 1, 2, 3].map((index) => ({ breed: formValue(formData, `breed-${index}`), setQuantity: formValue(formData, `setQuantity-${index}`), comment: formValue(formData, `itemComment-${index}`) })).filter((item) => item.setQuantity).map((item) => ({ breed: item.breed, setQuantity: Number(item.setQuantity), comment: item.comment })); await createIncubationBatch(user.id, incubationSchema.parse({ name: formData.get("name"), birdType: formData.get("birdType"), setDate: formData.get("setDate"), eggSource: formData.get("eggSource") || "OWN", cashCost: formValue(formData, "cashCost"), productionCost: formValue(formData, "productionCost"), comment: formValue(formData, "comment"), items })); done(formData, "/poultry/incubation", "created"); }
export async function updateIncubationItemAction(formData: FormData) { const user = await requireUser(); await updateIncubationItem(user.id, incubationUpdateSchema.parse({ itemId: formData.get("itemId"), hatchDate: formData.get("hatchDate"), infertileQuantity: formData.get("infertileQuantity"), lossQuantity: formData.get("lossQuantity"), hatchedQuantity: formData.get("hatchedQuantity") })); done(formData, "/poultry/incubation", "result"); }
export async function createBatchFromIncubationAction(formData: FormData) { const user = await requireUser(); await createBatchFromIncubation(user.id, required(formData, "itemId")); done(formData, "/poultry/flock", "hatched"); }

export async function createEggCollectionAction(formData: FormData) { const user = await requireUser(); await createEggCollection(user.id, eggCollectionSchema.parse({ batchId: formValue(formData, "batchId"), breed: formValue(formData, "breed"), quantity: formData.get("quantity"), operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") })); done(formData, "/poultry/eggs", "collected"); }
export async function deleteEggCollectionAction(formData: FormData) { const user = await requireUser(); await softDeleteEggCollection(user.id, required(formData, "id")); done(formData, "/poultry/eggs", "deleted"); }
export async function createOperationalExpenseAction(formData: FormData) { const user = await requireUser(); await createOperationalExpense(user.id, operationalExpenseSchema.parse({ categoryId: formData.get("categoryId"), batchId: formValue(formData, "batchId"), incubationBatchId: formValue(formData, "incubationBatchId"), amount: formData.get("amount"), operationDate: formData.get("operationDate"), description: formData.get("description") })); done(formData, "/poultry/expenses", "expense"); }
export async function deleteOperationalExpenseAction(formData: FormData) { const user = await requireUser(); await softDeleteOperationalExpense(user.id, required(formData, "id")); done(formData, "/poultry/expenses", "deleted"); }
