"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";

import { requireUser } from "@/server/auth";
import { batchSchema, createBatchFromIncubation, createFeedPurchase, createFeedUsage, createIncubationBatch, createOperationalExpense, createPoultryBatch, createPoultryMovement, createPoultrySale, feedPurchaseSchema, feedUsageSchema, formValue, incubationSchema, incubationUpdateSchema, movementSchema, operationalExpenseSchema, saleSchema, softDeletePoultrySale, updateIncubationItem, updatePoultrySale } from "@/server/poultry";

const refresh = () => ["/dashboard", "/poultry", "/projects", "/reports"].forEach((path) => revalidatePath(path));
const requireValue = (formData: FormData, name: string) => { const value = formData.get(name); if (typeof value !== "string") throw new Error("Перевірте форму."); return value; };
const done = (key: string) => { refresh(); redirect(`/poultry?${key}=1`); };

export async function createPoultryBatchAction(formData: FormData) { const user = await requireUser(); await createPoultryBatch(user.id, batchSchema.parse({ name: formData.get("name"), birdType: formData.get("birdType"), breed: formValue(formData, "breed"), startDate: formData.get("startDate"), quantity: formData.get("quantity"), source: formData.get("source"), comment: formValue(formData, "comment") })); done("batch"); }
export async function createPoultryMovementAction(formData: FormData) { const user = await requireUser(); await createPoultryMovement(user.id, movementSchema.parse({ batchId: formData.get("batchId"), type: formData.get("type"), quantity: formData.get("quantity"), operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") })); done("movement"); }
export async function createPoultrySaleAction(formData: FormData) { const user = await requireUser(); await createPoultrySale(user.id, saleSchema.parse({ batchId: formValue(formData, "batchId"), buyer: formValue(formData, "buyer"), itemName: formData.get("itemName"), quantity: formValue(formData, "quantity") ? Number(formValue(formData, "quantity")) : null, weightKg: formValue(formData, "weightKg"), price: formValue(formData, "price"), totalAmount: formValue(formData, "totalAmount"), operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") })); done("sale"); }
export async function deletePoultrySaleAction(formData: FormData) { const user = await requireUser(); await softDeletePoultrySale(user.id, requireValue(formData, "id")); done("saleDeleted"); }
export async function createFeedPurchaseAction(formData: FormData) { const user = await requireUser(); await createFeedPurchase(user.id, feedPurchaseSchema.parse({ name: formData.get("name"), type: formValue(formData, "type"), bagSizeKg: formValue(formData, "bagSizeKg"), bags: formData.get("bags"), totalAmount: formData.get("totalAmount"), operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") })); done("feed"); }
export async function createFeedUsageAction(formData: FormData) { const user = await requireUser(); await createFeedUsage(user.id, { ...feedUsageSchema.parse({ lotId: formData.get("lotId"), batchId: formData.get("batchId"), bags: formData.get("bags"), operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") }), type: formData.get("type") === "FINISHED" ? "FINISHED" : "ASSIGNED" }); done("feedUsage"); }
export async function updatePoultrySaleAction(formData: FormData) { const user = await requireUser(); await updatePoultrySale(user.id, requireValue(formData, "id"), saleSchema.parse({ batchId: formValue(formData, "batchId"), buyer: formValue(formData, "buyer"), itemName: formData.get("itemName"), quantity: formValue(formData, "quantity") ? Number(formValue(formData, "quantity")) : null, weightKg: formValue(formData, "weightKg"), price: formValue(formData, "price"), totalAmount: formValue(formData, "totalAmount"), operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") })); done("saleUpdated"); }
export async function createIncubationAction(formData: FormData) { const user = await requireUser(); const items = [0, 1, 2, 3].map((index) => ({ breed: formValue(formData, `breed-${index}`), setQuantity: formValue(formData, `setQuantity-${index}`), comment: formValue(formData, `itemComment-${index}`) })).filter((item) => item.breed && item.setQuantity).map((item) => ({ breed: item.breed!, setQuantity: Number(item.setQuantity), comment: item.comment })); await createIncubationBatch(user.id, incubationSchema.parse({ name: formData.get("name"), birdType: formData.get("birdType"), setDate: formData.get("setDate"), comment: formValue(formData, "comment"), items })); done("incubation"); }
export async function updateIncubationItemAction(formData: FormData) { const user = await requireUser(); await updateIncubationItem(user.id, incubationUpdateSchema.parse({ itemId: formData.get("itemId"), infertileQuantity: formData.get("infertileQuantity"), lossQuantity: formData.get("lossQuantity"), hatchedQuantity: formData.get("hatchedQuantity") })); done("incubationUpdated"); }
export async function createBatchFromIncubationAction(formData: FormData) { const user = await requireUser(); await createBatchFromIncubation(user.id, requireValue(formData, "itemId")); done("batchFromIncubation"); }
export async function createOperationalExpenseAction(formData: FormData) { const user = await requireUser(); await createOperationalExpense(user.id, operationalExpenseSchema.parse({ categoryId: formData.get("categoryId"), batchId: formValue(formData, "batchId"), amount: formData.get("amount"), operationDate: formData.get("operationDate"), description: formData.get("description") })); done("expense"); }
