"use server";

import { revalidatePath } from "next/cache";
import { redirect } from "next/navigation";

import { requireUser } from "@/server/auth";
import { batchSchema, createBatchFromIncubation, createEggCollection, createFeedAdjustment, createFeedProduct, createFeedPurchase, createFeedRate, createFeedUsage, createIncubationBatch, createOperationalExpense, createPoultryBatch, createPoultryBreed, createPoultryCategory, createPoultryMovement, createPoultrySale, createPoultryTransfer, createSlaughter, deleteUnusedFeedProduct, deleteUnusedPoultryCategory, eggCollectionSchema, feedAdjustmentSchema, feedProductCatalogSchema, feedProductSettingsSchema, feedPurchaseSchema, feedRateSchema, feedUnitSettingsSchema, feedUsageSchema, formValue, incubationSchema, incubationUpdateSchema, movePoultryBreed, movePoultryCategory, movementSchema, operationalExpenseSchema, poultryBreedSettingsSchema, poultryCategorySettingsSchema, reconcileFlock, reconciliationSchema, saleSchema, setPoultryBreedArchived, setPoultryCategoryArchived, slaughterSchema, softDeleteEggCollection, softDeleteOperationalExpense, softDeletePoultrySale, transferSchema, updateFeedProductCatalog, updateFeedProductSettings, updateFeedUnitSettings, updateIncubationItem, updatePoultryBreed, updatePoultryCategory, updatePoultrySale } from "@/server/poultry";

const refresh = () => ["/dashboard", "/poultry", "/poultry/flock", "/poultry/feed", "/poultry/eggs", "/poultry/analytics", "/poultry/settings", "/projects", "/reports", "/finance"].forEach((path) => revalidatePath(path));
const required = (formData: FormData, name: string) => { const value = formData.get(name); if (typeof value !== "string") throw new Error("Перевірте форму."); return value; };
const done = (formData: FormData, fallbackPath: string, key: string) => {
  refresh();
  const requested = formValue(formData, "returnTo");
  const safePath = requested?.startsWith("/poultry") && !requested.startsWith("//") ? requested : fallbackPath;
  const target = new URL(safePath, "http://fevora.local");
  target.searchParams.set(key, "1");
  redirect(`${target.pathname}${target.search}${target.hash}`);
};
const settingsError = (path: string, error: unknown) => { const message = error instanceof Error ? error.message : "Не удалось сохранить"; const code = message.includes("существует") ? "duplicate" : message.includes("истори") || message.includes("только архивировать") ? "used" : "protected"; redirect(`${path}?error=${code}`); };

export async function createPoultryBatchAction(formData: FormData) {
  const user = await requireUser();
  const breeds = [0, 1, 2, 3].map((index) => ({ name: formValue(formData, `breed-${index}`), quantity: formValue(formData, `breedQuantity-${index}`) })).filter((item) => item.quantity).map((item) => ({ name: item.name, quantity: Number(item.quantity) }));
  await createPoultryBatch(user.id, batchSchema.parse({ name: formData.get("name"), birdType: formData.get("birdType"), breed: formValue(formData, "breed"), breeds: breeds.length ? breeds : undefined, startDate: formData.get("startDate"), acquisitionDate: formData.get("acquisitionDate") || formData.get("startDate"), ageAtAcquisitionDays: formValue(formData, "ageAtAcquisitionDays") ? Number(formValue(formData, "ageAtAcquisitionDays")) : null, quantity: formData.get("quantity"), source: formData.get("source"), cashCost: formValue(formData, "cashCost"), productionValue: formValue(formData, "productionValue"), comment: formValue(formData, "comment") }));
  done(formData, "/poultry/flock", "batch");
}

export async function createPoultryMovementAction(formData: FormData) { const user = await requireUser(); await createPoultryMovement(user.id, movementSchema.parse({ batchId: formData.get("batchId"), type: formData.get("type"), quantity: formData.get("quantity"), operationDate: formData.get("operationDate"), reason: formValue(formData, "reason"), comment: formValue(formData, "comment") })); done(formData, "/poultry/flock", "movement"); }
export async function reconcileFlockAction(formData: FormData) { const user = await requireUser(); await reconcileFlock(user.id, reconciliationSchema.parse({ batchId: formData.get("batchId"), actualQuantity: formData.get("actualQuantity"), operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") })); done(formData, "/poultry/flock", "reconciled"); }
export async function createPoultryTransferAction(formData: FormData) { const user = await requireUser(); await createPoultryTransfer(user.id, transferSchema.parse({ sourceBatchId: formData.get("sourceBatchId"), destinationBatchId: formValue(formData, "destinationBatchId"), destinationName: formValue(formData, "destinationName"), quantity: formData.get("quantity"), operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") })); done(formData, "/poultry/flock", "transfer"); }
export async function createSlaughterAction(formData: FormData) { const user = await requireUser(); await createSlaughter(user.id, slaughterSchema.parse({ batchId: formData.get("batchId"), quantity: formData.get("quantity"), purpose: formData.get("purpose"), carcassWeightKg: formValue(formData, "carcassWeightKg"), operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") })); done(formData, "/poultry/flock", "slaughter"); }

const saleInput = (formData: FormData) => saleSchema.parse({ saleType: formData.get("saleType") || "LIVE_BIRD", batchId: formValue(formData, "batchId"), slaughterId: formValue(formData, "slaughterId"), buyer: formValue(formData, "buyer"), buyerPhone: formValue(formData, "buyerPhone"), itemName: formData.get("itemName"), quantity: formValue(formData, "quantity") ? Number(formValue(formData, "quantity")) : null, weightKg: formValue(formData, "weightKg"), price: formValue(formData, "price"), totalAmount: formValue(formData, "totalAmount"), operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") });
export async function createPoultrySaleAction(formData: FormData) { const user = await requireUser(); await createPoultrySale(user.id, saleInput(formData)); done(formData, "/poultry/sales", "sale"); }
export async function updatePoultrySaleAction(formData: FormData) { const user = await requireUser(); await updatePoultrySale(user.id, required(formData, "id"), saleInput(formData)); done(formData, "/poultry/sales", "updated"); }
export async function deletePoultrySaleAction(formData: FormData) { const user = await requireUser(); await softDeletePoultrySale(user.id, required(formData, "id")); done(formData, "/poultry/sales", "deleted"); }

export async function createFeedPurchaseAction(formData: FormData) { const user = await requireUser(); await createFeedPurchase(user.id, feedPurchaseSchema.parse({ name: formData.get("name"), type: formValue(formData, "type"), unit: formData.get("unit") || "BAG", quantity: formValue(formData, "quantity"), bags: formValue(formData, "bags") ? Number(formValue(formData, "bags")) : undefined, bagSizeKg: formValue(formData, "bagSizeKg"), householdUnitName: formValue(formData, "householdUnitName"), householdUnitKg: formValue(formData, "householdUnitKg"), totalAmount: formData.get("totalAmount"), deliveryAmount: formValue(formData, "deliveryAmount"), supplier: formValue(formData, "supplier"), operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") })); done(formData, "/poultry/feed", "purchase"); }
export async function createFeedUsageAction(formData: FormData) { const user = await requireUser(); await createFeedUsage(user.id, { ...feedUsageSchema.parse({ lotId: formData.get("lotId"), batchId: formValue(formData, "batchId"), purpose: formValue(formData, "purpose"), unit: formData.get("unit") || "BAG", quantity: formValue(formData, "quantity"), bags: formValue(formData, "bags") ? Number(formValue(formData, "bags")) : undefined, operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") }), type: formData.get("type") === "FINISHED" ? "FINISHED" : "ASSIGNED" }); done(formData, "/poultry/feed", "usage"); }
export async function createFeedRateAction(formData: FormData) { const user = await requireUser(); await createFeedRate(user.id, feedRateSchema.parse({ batchId: formData.get("batchId"), productId: formData.get("productId"), unit: formData.get("unit"), dailyQuantity: formData.get("dailyQuantity"), effectiveFrom: formData.get("effectiveFrom"), comment: formValue(formData, "comment") })); done(formData, "/poultry/feed", "rate"); }
export async function createFeedAdjustmentAction(formData: FormData) { const user = await requireUser(); await createFeedAdjustment(user.id, feedAdjustmentSchema.parse({ productId: formData.get("productId"), actualKg: formData.get("actualKg"), operationDate: formData.get("operationDate"), comment: formValue(formData, "comment") })); done(formData, "/poultry/feed", "adjustment"); }
export async function updateFeedProductSettingsAction(formData: FormData) { const user = await requireUser(); await updateFeedProductSettings(user.id, feedProductSettingsSchema.parse({ productId: formData.get("productId"), type: formValue(formData, "type"), minimumStockKg: formData.get("minimumStockKg") })); done(formData, "/poultry/feed/stock", "updated"); }
export async function updateFeedUnitSettingsAction(formData: FormData) { const user = await requireUser(); await updateFeedUnitSettings(user.id, feedUnitSettingsSchema.parse({ productId: formData.get("productId"), bagSizeKg: formValue(formData, "bagSizeKg"), householdUnitName: formValue(formData, "householdUnitName"), householdUnitKg: formValue(formData, "householdUnitKg") })); done(formData, "/poultry/settings/feed-units", "unitsSaved"); }
export async function createFeedProductAction(formData: FormData) { const user = await requireUser(); try { await createFeedProduct(user.id, feedProductCatalogSchema.parse({ name: formData.get("name"), type: formValue(formData, "type") })); } catch (error) { settingsError("/poultry/settings/feed-products", error); } done(formData, "/poultry/settings/feed-products", "feedProductSaved"); }
export async function updateFeedProductCatalogAction(formData: FormData) { const user = await requireUser(); try { await updateFeedProductCatalog(user.id, feedProductCatalogSchema.parse({ id: formData.get("id"), name: formData.get("name"), type: formValue(formData, "type") })); } catch (error) { settingsError("/poultry/settings/feed-products", error); } done(formData, "/poultry/settings/feed-products", "feedProductSaved"); }
export async function deleteFeedProductAction(formData: FormData) { const user = await requireUser(); try { await deleteUnusedFeedProduct(user.id, required(formData, "id")); } catch (error) { settingsError("/poultry/settings/feed-products", error); } done(formData, "/poultry/settings/feed-products", "feedProductDeleted"); }

export async function createPoultryCategoryAction(formData: FormData) { const user = await requireUser(); try { await createPoultryCategory(user.id, poultryCategorySettingsSchema.parse({ name: formData.get("name"), icon: formValue(formData, "icon") })); } catch (error) { settingsError("/poultry/settings/categories", error); } done(formData, "/poultry/settings/categories", "categorySaved"); }
export async function updatePoultryCategoryAction(formData: FormData) { const user = await requireUser(); try { await updatePoultryCategory(user.id, poultryCategorySettingsSchema.parse({ id: formData.get("id"), name: formData.get("name"), icon: formValue(formData, "icon") })); } catch (error) { settingsError("/poultry/settings/categories", error); } done(formData, "/poultry/settings/categories", "categorySaved"); }
export async function archivePoultryCategoryAction(formData: FormData) { const user = await requireUser(); try { await setPoultryCategoryArchived(user.id, required(formData, "id"), formData.get("archived") === "1"); } catch (error) { settingsError("/poultry/settings/categories", error); } done(formData, "/poultry/settings/categories", "categorySaved"); }
export async function movePoultryCategoryAction(formData: FormData) { const user = await requireUser(); await movePoultryCategory(user.id, required(formData, "id"), formData.get("direction") === "DOWN" ? "DOWN" : "UP"); done(formData, "/poultry/settings/categories", "categorySaved"); }
export async function deletePoultryCategoryAction(formData: FormData) { const user = await requireUser(); try { await deleteUnusedPoultryCategory(user.id, required(formData, "id")); } catch (error) { settingsError("/poultry/settings/categories", error); } done(formData, "/poultry/settings/categories", "categoryDeleted"); }

export async function createPoultryBreedAction(formData: FormData) { const user = await requireUser(); try { await createPoultryBreed(user.id, poultryBreedSettingsSchema.parse({ name: formData.get("name") })); } catch (error) { settingsError("/poultry/settings/breeds", error); } done(formData, "/poultry/settings/breeds", "breedSaved"); }
export async function updatePoultryBreedAction(formData: FormData) { const user = await requireUser(); try { await updatePoultryBreed(user.id, poultryBreedSettingsSchema.parse({ id: formData.get("id"), name: formData.get("name") })); } catch (error) { settingsError("/poultry/settings/breeds", error); } done(formData, "/poultry/settings/breeds", "breedSaved"); }
export async function archivePoultryBreedAction(formData: FormData) { const user = await requireUser(); await setPoultryBreedArchived(user.id, required(formData, "id"), formData.get("archived") === "1"); done(formData, "/poultry/settings/breeds", "breedSaved"); }
export async function movePoultryBreedAction(formData: FormData) { const user = await requireUser(); await movePoultryBreed(user.id, required(formData, "id"), formData.get("direction") === "DOWN" ? "DOWN" : "UP"); done(formData, "/poultry/settings/breeds", "breedSaved"); }

export async function createIncubationAction(formData: FormData) { const user = await requireUser(); const items = [0, 1, 2, 3].map((index) => ({ breed: formValue(formData, `breed-${index}`), setQuantity: formValue(formData, `setQuantity-${index}`), comment: formValue(formData, `itemComment-${index}`) })).filter((item) => item.setQuantity).map((item) => ({ breed: item.breed, setQuantity: Number(item.setQuantity), comment: item.comment })); await createIncubationBatch(user.id, incubationSchema.parse({ name: formData.get("name"), birdType: formData.get("birdType"), setDate: formData.get("setDate"), eggSource: formData.get("eggSource") || "OWN", cashCost: formValue(formData, "cashCost"), productionCost: formValue(formData, "productionCost"), comment: formValue(formData, "comment"), items })); done(formData, "/poultry/incubation", "created"); }
export async function updateIncubationItemAction(formData: FormData) { const user = await requireUser(); await updateIncubationItem(user.id, incubationUpdateSchema.parse({ itemId: formData.get("itemId"), hatchDate: formData.get("hatchDate"), infertileQuantity: formData.get("infertileQuantity"), lossQuantity: formData.get("lossQuantity"), hatchedQuantity: formData.get("hatchedQuantity") })); done(formData, "/poultry/incubation", "result"); }
export async function createBatchFromIncubationAction(formData: FormData) { const user = await requireUser(); await createBatchFromIncubation(user.id, required(formData, "itemId")); done(formData, "/poultry/flock", "hatched"); }

export async function createEggCollectionAction(formData: FormData) { const user = await requireUser(); await createEggCollection(user.id, eggCollectionSchema.parse({ batchId: formValue(formData, "batchId"), breed: formValue(formData, "breed"), quantity: formData.get("quantity"), operationDate: formData.get("operationDate"), collector: formValue(formData, "collector"), comment: formValue(formData, "comment") })); done(formData, "/poultry/eggs", "collected"); }
export async function deleteEggCollectionAction(formData: FormData) { const user = await requireUser(); await softDeleteEggCollection(user.id, required(formData, "id")); done(formData, "/poultry/eggs", "deleted"); }
export async function createOperationalExpenseAction(formData: FormData) { const user = await requireUser(); await createOperationalExpense(user.id, operationalExpenseSchema.parse({ categoryId: formData.get("categoryId"), batchId: formValue(formData, "batchId"), incubationBatchId: formValue(formData, "incubationBatchId"), amount: formData.get("amount"), operationDate: formData.get("operationDate"), description: formValue(formData, "description") ?? "Расход птицеводства" })); done(formData, "/poultry/expenses", "expense"); }
export async function deleteOperationalExpenseAction(formData: FormData) { const user = await requireUser(); await softDeleteOperationalExpense(user.id, required(formData, "id")); done(formData, "/poultry/expenses", "deleted"); }
