import Link from "next/link";

import { formatMoney } from "@/lib/money";
import { todayInputValue } from "@/lib/dates";
import { requireUser } from "@/server/auth";
import { getPoultryCategories, getPoultryDashboard } from "@/server/poultry";

import { createBatchFromIncubationAction, createFeedPurchaseAction, createFeedUsageAction, createIncubationAction, createOperationalExpenseAction, createPoultryBatchAction, createPoultryMovementAction, createPoultrySaleAction, deletePoultrySaleAction, updateIncubationItemAction } from "./actions";

const periods = { TODAY: "Сьогодні", WEEK: "Тиждень", MONTH: "Місяць", YEAR: "Рік" } as const;
const notice = (params: Record<string, string | string[] | undefined>) => params.batch ? "Партію створено." : params.movement ? "Рух поголівʼя збережено." : params.sale ? "Продаж і один дохід Poultry збережено." : params.saleDeleted ? "Продаж та повʼязаний дохід виключено з розрахунків." : params.feed ? "Корм куплено: один expense і склад оновлено." : params.feedUsage ? "Мішки призначено партії без нового expense." : params.incubation ? "Закладку інкубації створено." : params.incubationUpdated ? "Показники інкубації оновлено." : params.batchFromIncubation ? "Партію створено з інкубації." : params.expense ? "Операційну витрату збережено." : null;

export default async function PoultryPage({ searchParams }: { searchParams: Promise<Record<string, string | string[] | undefined>> }) {
  const user = await requireUser();
  const params = await searchParams;
  const period = (typeof params.period === "string" && params.period in periods ? params.period : "MONTH") as keyof typeof periods;
  const [{ report, batches, lots, incubations, sales }, categories] = await Promise.all([getPoultryDashboard(user.id, period), getPoultryCategories(user.id)]);
  const date = todayInputValue();
  return <><header className="page-header"><div><p className="eyebrow">Проєкт · Птахівництво</p><h1>Птицеводство</h1><p className="muted">Один факт — один результат: продажи, склад и финансы не дублируются.</p></div><Link className="button primary" href="/add">+ Додати</Link></header>{notice(params) && <p className="notice">{notice(params)}</p>}<form className="period-tabs" action="/poultry">{Object.entries(periods).map(([value, label]) => <button key={value} name="period" value={value} className={period === value ? "active" : ""}>{label}</button>)}</form>
  <section className="metric-grid poultry-summary"><article><span>Доходи</span><strong className="income">{formatMoney(report.income)}</strong></article><article><span>Витрати</span><strong className="expense">{formatMoney(report.expense)}</strong></article><article><span>Результат</span><strong>{formatMoney(report.result)}</strong></article><article><span>Активні партії</span><strong>{batches.filter((batch) => batch.status === "ACTIVE").length}</strong></article></section>
  <section className="poultry-grid"><article className="panel"><h2>1. Поголівʼя · нова партія</h2><form action={createPoultryBatchAction} className="compact-form"><label>Назва / номер<input name="name" required placeholder="Бройлери №3" /></label><div className="form-grid"><label>Вид птиці<input name="birdType" required list="bird-types" placeholder="Бройлери" /></label><label>Порода<input name="breed" placeholder="Необовʼязково" /></label></div><div className="form-grid"><label>Дата початку<input name="startDate" type="date" required defaultValue={date} /></label><label>Стартова кількість<input name="quantity" required inputMode="numeric" /></label></div><label>Джерело<select name="source"><option value="PURCHASE">Покупка</option><option value="INCUBATION">Власна інкубація</option><option value="OTHER">Інше</option></select></label><label>Коментар<input name="comment" placeholder="Необовʼязково" /></label><button className="button primary">Створити партію</button></form><datalist id="bird-types"><option value="Кури"/><option value="Бройлери"/><option value="Качки"/><option value="Індокачки"/><option value="Несучки"/><option value="Інша птиця"/></datalist></article>
  <article className="panel"><h2>Рух поголівʼя</h2><form action={createPoultryMovementAction} className="compact-form"><label>Партія<select name="batchId" required><option value="" disabled selected>Оберіть активну партію</option>{batches.filter((batch) => batch.status === "ACTIVE").map((batch) => <option key={batch.id} value={batch.id}>{batch.name} · {batch.currentQuantity} гол.</option>)}</select></label><div className="form-grid"><label>Подія<select name="type"><option value="MORTALITY">Падіж</option><option value="FAMILY_USE">Залишено сімʼї / забій</option><option value="ADD">Додано</option><option value="TRANSFER">Переведення</option><option value="ADJUSTMENT">Коригування</option></select></label><label>Кількість<input name="quantity" required inputMode="numeric" /></label></div><label>Дата<input name="operationDate" type="date" required defaultValue={date} /></label><label>Коментар<input name="comment" placeholder="Необовʼязково" /></label><p className="muted">Залишено сімʼї та падіж зменшують партію, але не створюють дохід.</p><button className="button secondary">Зберегти рух</button></form></article></section>
  <section className="section-header"><div><p className="eyebrow">Поголівʼя</p><h2>Активні та завершені партії</h2></div></section><div className="poultry-cards">{batches.map((batch) => <article className="panel" key={batch.id}><div className="card-title"><b>{batch.name}</b><span>{batch.status === "ACTIVE" ? "Активна" : "Завершена"}</span></div><p>{batch.birdType}{batch.breed ? ` · ${batch.breed}` : ""}</p><strong>{batch.currentQuantity} гол.</strong><small>Старт: {batch.startingQuantity} · вік: {batch.ageDays} дн. · корм: {formatMoney(batch.feedCost.toString())}</small></article>)}{batches.length === 0 && <p className="empty">Партій поки немає.</p>}</div>
  <section className="poultry-grid"><article className="panel"><h2>2. Корма і склад · покупка</h2><form action={createFeedPurchaseAction} className="compact-form"><label>Назва корму<input name="name" required placeholder="ПК-5" /></label><div className="form-grid"><label>Тип<input name="type" placeholder="Комбікорм" /></label><label>Мішок, кг<input name="bagSizeKg" inputMode="decimal" placeholder="Необовʼязково" /></label></div><div className="form-grid"><label>Мішків<input name="bags" required inputMode="numeric" /></label><label>Загальна сума<input name="totalAmount" required inputMode="decimal" placeholder="0,00" /></label></div><label>Дата<input name="operationDate" type="date" required defaultValue={date} /></label><label>Коментар<input name="comment" placeholder="Необовʼязково" /></label><button className="button primary">Купити корм</button></form></article>
  <article className="panel"><h2>Призначити / закінчити мішок</h2><form action={createFeedUsageAction} className="compact-form"><label>Складська партія<select name="lotId" required><option value="" disabled selected>Оберіть корм</option>{lots.filter((lot) => lot.availableBags > 0).map((lot) => <option value={lot.id} key={lot.id}>{lot.product.name} · доступно {lot.availableBags}/{lot.purchasedBags}</option>)}</select></label><label>Партія птиці<select name="batchId" required><option value="" disabled selected>Оберіть партію</option>{batches.filter((batch) => batch.status === "ACTIVE").map((batch) => <option value={batch.id} key={batch.id}>{batch.name}</option>)}</select></label><div className="form-grid"><label>Статус<select name="type"><option value="ASSIGNED">Призначити</option><option value="FINISHED">Мішок закінчився</option></select></label><label>Мішків<input name="bags" required inputMode="numeric" defaultValue="1" /></label></div><label>Дата<input name="operationDate" type="date" required defaultValue={date} /></label><label>Коментар<input name="comment" placeholder="Наприклад: відкрито для №3" /></label><button className="button secondary">Зберегти без витрати</button></form></article></section>
  <section className="section-header"><div><p className="eyebrow">Склад</p><h2>Корма</h2></div></section><div className="transaction-list">{lots.map((lot) => <div className="transaction-row" key={lot.id}><span><b>{lot.product.name}</b><small>Закуплено {lot.purchasedBags} · доступно {lot.availableBags} · {formatMoney(lot.costPerBag.toString())}/мішок</small></span><strong>{lot.availableBags} міш.</strong></div>)}{lots.length === 0 && <p className="empty">Корм на склад ще не надходив.</p>}</div>
  <section className="poultry-grid"><article className="panel"><h2>3. Продажі</h2><form action={createPoultrySaleAction} className="compact-form"><label>Партія (якщо застосовно)<select name="batchId"><option value="">Без привʼязки</option>{batches.filter((batch) => batch.status === "ACTIVE").map((batch) => <option value={batch.id} key={batch.id}>{batch.name} · {batch.currentQuantity} гол.</option>)}</select></label><div className="form-grid"><label>Покупець<input name="buyer" placeholder="Необовʼязково" /></label><label>Що продано<input name="itemName" required placeholder="Бройлери" /></label></div><div className="form-grid"><label>Кількість<input name="quantity" inputMode="numeric" placeholder="або вага" /></label><label>Вага, кг<input name="weightKg" inputMode="decimal" placeholder="або кількість" /></label></div><div className="form-grid"><label>Ціна (за кг/од.)<input name="price" inputMode="decimal" placeholder="180" /></label><label>Підсумок<input name="totalAmount" inputMode="decimal" placeholder="якщо названо явно" /></label></div><label>Дата<input name="operationDate" type="date" required defaultValue={date} /></label><label>Коментар<input name="comment" placeholder="Необовʼязково" /></label><button className="button primary">Зберегти продаж</button></form></article>
  <article className="panel"><h2>6. Операційні витрати</h2><form action={createOperationalExpenseAction} className="compact-form"><label>Категорія<select name="categoryId" required><option value="" disabled selected>Оберіть категорію</option>{categories.filter((category) => category.kind !== "INCOME" && category.name !== "Корма").map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><label>Партія (необовʼязково)<select name="batchId"><option value="">Загальна витрата</option>{batches.map((batch) => <option value={batch.id} key={batch.id}>{batch.name}</option>)}</select></label><div className="form-grid"><label>Сума<input name="amount" required inputMode="decimal" /></label><label>Дата<input name="operationDate" type="date" required defaultValue={date} /></label></div><label>Опис<input name="description" required placeholder="Лампочки в курник" /></label><button className="button secondary">Додати витрату</button></form></article></section>
  <section className="section-header"><div><p className="eyebrow">Продажі</p><h2>Останні продажі</h2></div></section><div className="transaction-list">{sales.map((sale) => <div className="transaction-row" key={sale.id}><span><b>{sale.itemName}</b><small>{sale.operationDate.toLocaleDateString("uk-UA")}{sale.buyer ? ` · ${sale.buyer}` : ""}{sale.batch ? ` · ${sale.batch.name}` : ""}</small></span><span className="row-actions"><strong className="income">+{formatMoney(sale.totalAmount.toString())}</strong><Link className="text-link" href={`/poultry/sales/${sale.id}`}>Редагувати</Link><form action={deletePoultrySaleAction}><input type="hidden" name="id" value={sale.id}/><button className="text-link">Видалити</button></form></span></div>)}{sales.length === 0 && <p className="empty">Продажів поки немає.</p>}</div>
  <section className="panel incubation-panel"><p className="eyebrow">4. Інкубація</p><h2>Нова закладка</h2><form action={createIncubationAction} className="compact-form"><div className="form-grid"><label>Назва / номер<input name="name" required placeholder="Закладка 30 червня" /></label><label>Вид птиці<input name="birdType" required placeholder="Кури" /></label></div><div className="form-grid"><label>Дата закладки<input name="setDate" type="date" required defaultValue={date} /></label><label>Коментар<input name="comment" placeholder="Необовʼязково" /></label></div><p className="muted">Одна фізична закладка може містити кілька порід.</p>{[0, 1, 2, 3].map((index) => <div className="form-grid" key={index}><label>Порода<input name={`breed-${index}`} required={index === 0} placeholder={index === 0 ? "R3A" : "Не додавати"}/></label><label>Заложено<input name={`setQuantity-${index}`} required={index === 0} inputMode="numeric" /></label></div>)}<button className="button primary">Створити закладку</button></form></section>
  <section className="section-header"><div><p className="eyebrow">Інкубація</p><h2>Закладки і вивід</h2></div></section><div className="incubation-list">{incubations.map((batch) => <article className="panel" key={batch.id}><div className="card-title"><b>{batch.name}</b><span>{batch.status === "ACTIVE" ? "Активна" : "Завершена"}</span></div><p>{batch.birdType} · {batch.setDate.toLocaleDateString("uk-UA")}</p>{batch.items.map((item) => <div className="incubation-item" key={item.id}><b>{item.breed}: {item.hatchedQuantity}/{item.setQuantity} · {item.hatchRate}%</b><form action={updateIncubationItemAction} className="inline-form"><input type="hidden" name="itemId" value={item.id}/><input name="infertileQuantity" inputMode="numeric" defaultValue={item.infertileQuantity}/><input name="lossQuantity" inputMode="numeric" defaultValue={item.lossQuantity}/><input name="hatchedQuantity" inputMode="numeric" defaultValue={item.hatchedQuantity}/><button className="text-link">Оновити</button></form><small>поля: неоплід · втрати · вилупилось</small>{item.hatchedQuantity > 0 && <form action={createBatchFromIncubationAction}><input type="hidden" name="itemId" value={item.id}/><button className="text-link">Створити партію з виводу</button></form>}</div>)}</article>)}{incubations.length === 0 && <p className="empty">Закладок інкубації поки немає.</p>}</div>
  <section className="poultry-grid"><article className="panel"><h2>Фінанси за категоріями</h2><div className="mini-list">{report.expensesByCategory.map((item) => <div key={item.name}><span>{item.name}</span><b className="expense">{formatMoney(item.amount)}</b></div>)}{report.expensesByCategory.length === 0 && <p className="muted">Витрат у цьому періоді немає.</p>}</div></article><article className="panel"><h2>Звіти</h2><p className="muted">У звіті враховані лише активні Poultry-транзакції за обраний період.</p><Link href="/reports" className="button secondary">Відкрити звіти</Link></article></section></>;
}
