import Link from "next/link";

import { formatMoney } from "@/lib/money";
import { requireUser } from "@/server/auth";
import { getFamilyReport } from "@/server/family";

const labels = { TODAY: "Сьогодні", WEEK: "Тиждень", MONTH: "Місяць", YEAR: "Рік" } as const;

export default async function ReportsPage({ searchParams }: { searchParams: Promise<{ period?: string }> }) { const user = await requireUser(); const { period } = await searchParams; const current = period && period in labels ? period as keyof typeof labels : "MONTH"; const report = await getFamilyReport(user.id, current); return <><header className="page-header"><div><p className="eyebrow">Звіти · Сімʼя</p><h1>Підсумок за період</h1></div><Link href="/family" className="text-link">До Family</Link></header><form className="period-tabs" action="/reports">{Object.entries(labels).map(([value, label]) => <button name="period" value={value} className={current === value ? "active" : ""} key={value}>{label}</button>)}</form><section className="metric-grid family-summary"><article><span>Доходи</span><strong className="income">{formatMoney(report.income)}</strong></article><article><span>Витрати</span><strong className="expense">{formatMoney(report.expense)}</strong></article><article><span>Сбереження</span><strong>{formatMoney(report.savings)}</strong></article><article><span>Баланс</span><strong>{formatMoney(report.balance)}</strong></article></section><section className="family-grid"><article className="panel"><h2>Витрати за категоріями</h2><div className="mini-list">{report.expensesByCategory.map((item) => <div key={item.name}><span>{item.name}</span><b className="expense">{formatMoney(item.amount)}</b></div>)}{report.expensesByCategory.length === 0 && <p className="muted">Немає витрат за цей період.</p>}</div></article><article className="panel"><h2>Доходи за категоріями</h2><div className="mini-list">{report.incomeByCategory.map((item) => <div key={item.name}><span>{item.name}</span><b className="income">{formatMoney(item.amount)}</b></div>)}{report.incomeByCategory.length === 0 && <p className="muted">Немає доходів за цей період.</p>}</div></article></section></>; }
