import Link from "next/link";

import { formatMoney } from "@/lib/money";
import { requireUser } from "@/server/auth";
import { getFamilyReport } from "@/server/family";
import { getPoultryDashboard } from "@/server/poultry";

const labels = { TODAY: "Сьогодні", WEEK: "Тиждень", MONTH: "Місяць", YEAR: "Рік" } as const;

export default async function ReportsPage({ searchParams }: { searchParams: Promise<{ period?: string; project?: string }> }) { const user = await requireUser(); const { period, project } = await searchParams; const current = period && period in labels ? period as keyof typeof labels : "MONTH"; const poultry = project === "poultry"; const [family, poultryData] = await Promise.all([getFamilyReport(user.id, current), getPoultryDashboard(user.id, current)]); const report = poultry ? poultryData.report : family; const financialResult = poultry ? poultryData.report.result : family.balance; return <><header className="page-header"><div><p className="eyebrow">Звіти · {poultry ? "Птахівництво" : "Сімʼя"}</p><h1>Підсумок за період</h1></div><Link href={poultry ? "/poultry" : "/family"} className="text-link">До проєкту</Link></header><form className="period-tabs" action="/reports"><button name="project" value="family" className={!poultry ? "active" : ""}>Сімʼя</button><button name="project" value="poultry" className={poultry ? "active" : ""}>Птахівництво</button>{Object.entries(labels).map(([value, label]) => <button name="period" value={value} className={current === value ? "active" : ""} key={value}>{label}</button>)}</form><section className="metric-grid family-summary"><article><span>Доходи</span><strong className="income">{formatMoney(report.income)}</strong></article><article><span>Витрати</span><strong className="expense">{formatMoney(report.expense)}</strong></article>{poultry ? <><article><span>Фінансовий результат</span><strong>{formatMoney(financialResult)}</strong></article><article><span>Продажі</span><strong>{poultryData.sales.length}</strong></article></> : <><article><span>Сбереження</span><strong>{formatMoney(family.savings)}</strong></article><article><span>Баланс</span><strong>{formatMoney(financialResult)}</strong></article></>}</section><section className="family-grid"><article className="panel"><h2>Витрати за категоріями</h2><div className="mini-list">{report.expensesByCategory.map((item) => <div key={item.name}><span>{item.name}</span><b className="expense">{formatMoney(item.amount)}</b></div>)}{report.expensesByCategory.length === 0 && <p className="muted">Немає витрат за цей період.</p>}</div></article>{!poultry && <article className="panel"><h2>Доходи за категоріями</h2><div className="mini-list">{family.incomeByCategory.map((item) => <div key={item.name}><span>{item.name}</span><b className="income">{formatMoney(item.amount)}</b></div>)}{family.incomeByCategory.length === 0 && <p className="muted">Немає доходів за цей період.</p>}</div></article>} {poultry && <article className="panel"><h2>Показники Poultry</h2><p className="muted">Активні партії: {poultryData.batches.filter((batch) => batch.status === "ACTIVE").length}</p><p className="muted">Корм на складі: {poultryData.lots.reduce((total, lot) => total + lot.availableBags, 0)} міш.</p></article>}</section></>; }
