import Link from "next/link";

import { EmptyState } from "@/components/ui/empty-state";
import { todayInputValue } from "@/lib/dates";
import { formatMoney } from "@/lib/money";
import { requireUser } from "@/server/auth";
import { getCosmetologyAppointments, getCosmetologyDashboard } from "@/server/cosmetology";
import { createCosmetologyAppointmentAction } from "../actions";

export default async function VisitsPage() {
  const user = await requireUser();
  const [dashboard, appointments] = await Promise.all([getCosmetologyDashboard(user.id), getCosmetologyAppointments(user.id)]);
  const scheduled = appointments.filter((item) => item.status === "SCHEDULED");
  const completed = appointments.filter((item) => item.status === "COMPLETED");
  return <><header className="page-header"><div><p className="eyebrow">Косметология · Записи</p><h1>Новая запись</h1><p className="muted">Запись не создаёт доход и не списывает товар. Закройте процедуру после фактического выполнения.</p></div><Link href="/cosmetology" className="button secondary">Назад</Link></header>
    <section className="family-grid"><article className="app-card"><h2>Записать клиента</h2><form action={createCosmetologyAppointmentAction} className="compact-form"><label>Клиент<select name="clientId" defaultValue=""><option value="">Новый или не выбран</option>{dashboard.clients.map((client) => <option key={client.id} value={client.id}>{client.displayName ?? `${client.lastName} ${client.firstName}`} {client.phone !== "Не указан" ? `· ${client.phone}` : ""}</option>)}</select></label><div className="form-grid"><label>Имя нового клиента<input name="clientName" placeholder="Например, Оля"/></label><label>Телефон<input name="phone" type="tel" placeholder="Необязательно"/></label></div><label>Instagram / ссылка<input name="contactValue" placeholder="Необязательно"/></label><label>Услуга<select name="procedureTemplateId" defaultValue=""><option value="">Ввести вручную</option>{dashboard.templates.map((template) => <option key={template.id} value={template.id}>{template.name}{template.basePrice ? ` · ${formatMoney(template.basePrice.toString())}` : ""}</option>)}</select></label><div className="form-grid"><label>Или название услуги<input name="procedureName" placeholder="Чистка лица"/></label><label>Плановая цена<input name="plannedAmount" inputMode="decimal" placeholder="Из прайса"/></label></div><div className="form-grid"><label>Дата<input name="operationDate" type="date" required defaultValue={todayInputValue()}/></label><label>Время<input name="scheduledTime" type="time" min="08:00" max="20:00"/></label></div><label>Длительность<select name="durationMinutes" defaultValue="60"><option value="15">15 мин</option><option value="30">30 мин</option><option value="45">45 мин</option><option value="60">1 час</option><option value="75">1 ч 15 мин</option><option value="90">1 ч 30 мин</option><option value="120">2 часа</option></select></label><fieldset><legend>Предоплата — укажите только полученные суммы</legend><div className="form-grid"><label>Наличные<input name="cashAmount" inputMode="decimal" defaultValue="0"/></label><label>Monobank<input name="monoAmount" inputMode="decimal" defaultValue="0"/></label><label>ПриватБанк<input name="privatAmount" inputMode="decimal" defaultValue="0"/></label></div></fieldset><label>Заметка<input name="comment" placeholder="Необязательно"/></label><button className="button primary">Создать запись</button></form></article><article className="app-card"><h2>Как это работает</h2><p className="muted">Запись сохраняет клиента, время, услугу и предоплату. Деньги и товары не списываются до закрытия процедуры.</p><Link href="/cosmetology/procedures" className="text-link">Настроить услуги и техкарты</Link></article></section>
    <section className="section-header"><div><p className="eyebrow">Календарь</p><h2>Ожидают проведения</h2></div></section><div className="transaction-list">{scheduled.map((item) => <Link href={`/cosmetology/visits/${item.id}`} className="transaction-row" key={item.id}><span><b>{item.procedureName}</b><small>{item.client.displayName ?? `${item.client.lastName} ${item.client.firstName}`} · {item.operationDate.toLocaleDateString("ru-RU")}{item.scheduledTime ? ` · ${item.scheduledTime}` : ""}</small></span><strong>Закрыть →</strong></Link>)}</div>{!scheduled.length && <EmptyState title="Записей пока нет" description="Добавьте первую запись — финансы и склад не изменятся до закрытия процедуры."/>}
    <section className="section-header"><div><p className="eyebrow">История</p><h2>Завершённые процедуры</h2></div></section><div className="transaction-list">{completed.slice(0, 10).map((item) => <Link href={`/cosmetology/visits/${item.id}`} className="transaction-row" key={item.id}><span><b>{item.procedureName}</b><small>{item.client.displayName ?? `${item.client.lastName} ${item.client.firstName}`} · себестоимость {formatMoney(item.costAmount.toString())}</small></span><strong className="income">+{formatMoney(item.paymentAmount.toString())}</strong></Link>)}</div></>;
}
