import Link from "next/link";

import { EmptyState } from "@/components/ui/empty-state";
import { formatMoney } from "@/lib/money";
import { todayInputValue } from "@/lib/dates";
import { requireUser } from "@/server/auth";
import { getInfoDashboard } from "@/server/infobusiness";
import { createInfoExpenseAction, createInfoExpenseCategoryAction, updateInfoExpenseCategoryAction } from "../actions";

export default async function InfoExpensesPage() {
  const user = await requireUser(); const { products, categories, expenses } = await getInfoDashboard(user.id);
  return <><header className="page-header"><div><p className="eyebrow">Инфобизнес · Расходы</p><h1>Расходы обучения</h1><p className="muted">Пользователь сам выбирает: расход курса или общий расход Инфобизнеса.</p></div><Link href="/infobusiness" className="button secondary">Назад</Link></header>
    <section className="family-grid"><article className="app-card"><h2>Новый расход</h2><form action={createInfoExpenseAction} className="compact-form"><label>Сумма<input name="amount" required inputMode="decimal" placeholder="500"/></label><label>Категория<select name="categoryId" defaultValue=""><option value="">Выберите категорию</option>{categories.map((category) => <option key={category.id} value={category.id}>{category.name}</option>)}</select></label><label>+ Добавить категорию в этой форме<input name="newCategoryName" placeholder="Например: Монтаж"/></label><label>К чему относится<select name="productId" defaultValue=""><option value="">Общий расход Инфобизнеса</option>{products.filter((product) => product.status !== "ARCHIVED").map((product) => <option key={product.id} value={product.id}>{product.name}</option>)}</select></label><div className="form-grid"><label>Дата<input name="operationDate" type="date" required defaultValue={todayInputValue()}/></label><label>Название сервиса<input name="serviceName" placeholder="Только для сервисов"/></label></div><label>Описание<input name="description" required placeholder="Например: реклама запуска"/></label><label>Комментарий<input name="comment" placeholder="Необязательно"/></label><button className="button primary">Сохранить расход</button></form></article><article className="app-card"><h2>Без автоперераспределения</h2><p className="muted">Общий расход уменьшает только общий результат Инфобизнеса. Он не влияет на прибыль отдельных курсов.</p><form action={createInfoExpenseCategoryAction} className="inline-form"><input name="name" required placeholder="Своя категория"/><button className="button secondary">Добавить</button></form></article></section>
    <section className="section-header"><div><p className="eyebrow">Категории</p><h2>Управление категориями</h2></div></section><div className="mini-list app-card">{categories.map((category) => <form action={updateInfoExpenseCategoryAction} className="inline-form" key={category.id}><input type="hidden" name="id" value={category.id}/><input name="name" defaultValue={category.name}/><label className="checkbox-label"><input name="isArchived" type="checkbox"/>Архив</label><button className="text-link">Сохранить</button></form>)}</div>
    <section className="section-header"><div><p className="eyebrow">История</p><h2>Расходы за период</h2></div><Link className="text-link" href="/infobusiness/analytics">Аналитика</Link></section><div className="transaction-list">{expenses.map((expense) => <Link href={`/infobusiness/expenses/${expense.id}`} className="transaction-row" key={expense.id}><span><b>{expense.transaction.description ?? expense.category.name}</b><small>{expense.category.name} · {expense.product?.name ?? "Общий расход"} · {expense.transaction.operationDate.toLocaleDateString("ru-RU")}</small></span><strong className="expense">−{formatMoney(expense.transaction.amount.toString())}</strong></Link>)}</div>{expenses.length === 0 && <EmptyState title="Расходов пока нет" description="Добавьте расход курса или общий расход Инфобизнеса."/>}</>;
}
