import Link from "next/link";

import { EmptyState } from "@/components/ui/empty-state";
import { formatMoney } from "@/lib/money";
import { todayInputValue } from "@/lib/dates";
import { requireUser } from "@/server/auth";
import { getPoultryCategories, getPoultryDashboard } from "@/server/poultry";
import { createOperationalExpenseAction } from "../actions";

export default async function PoultryExpensesPage() { const user = await requireUser(); const [{ batches, report }, categories] = await Promise.all([getPoultryDashboard(user.id), getPoultryCategories(user.id)]); const expenseCategories = categories.filter((category) => category.kind !== "INCOME" && category.name !== "Корма"); return <><header className="page-header"><div><p className="eyebrow">Птицеводство</p><h1>Операционные расходы</h1><p className="muted">Расходы на материалы, содержание, препараты и другое.</p></div><Link href="/poultry" className="button secondary">Назад</Link></header><section className="family-grid"><article className="app-card"><h2>Добавить расход</h2><form action={createOperationalExpenseAction} className="compact-form"><label>Категория<select name="categoryId" required defaultValue=""><option value="" disabled>Выберите категорию</option>{expenseCategories.map((category) => <option value={category.id} key={category.id}>{category.name}</option>)}</select></label><label>Партия (необязательно)<select name="batchId"><option value="">Общий расход фермы</option>{batches.map((batch) => <option value={batch.id} key={batch.id}>{batch.name}</option>)}</select></label><div className="form-grid"><label>Сумма<input name="amount" required inputMode="decimal" placeholder="70"/></label><label>Дата<input name="operationDate" type="date" required defaultValue={todayInputValue()}/></label></div><label>Описание<input name="description" required placeholder="Лампочки в курятник"/></label><button className="button primary">Сохранить расход</button></form></article><article className="app-card"><h2>За выбранный период</h2><strong className="expense">{formatMoney(report.expense)}</strong><div className="mini-list">{report.expensesByCategory.map((item) => <div key={item.name}><span>{item.name}</span><b className="expense">{formatMoney(item.amount)}</b></div>)}</div>{report.expensesByCategory.length===0 && <p className="muted">Расходов за этот период нет.</p>}</article></section>{expenseCategories.length === 0 && <EmptyState title="Категории расходов не найдены" description="После запуска seed-категории Poultry будут доступны здесь."/>}</>; }
